//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC_Endpoint_Client.ReporteeArchiveStreamedEC2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AltinnFault", Namespace="http://www.altinn.no/services/common/fault/2009/10")]
    [System.SerializableAttribute()]
    public partial class AltinnFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AltinnErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AltinnExtendedErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AltinnLocalizedErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AltinnErrorMessage {
            get {
                return this.AltinnErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.AltinnErrorMessageField, value) != true)) {
                    this.AltinnErrorMessageField = value;
                    this.RaisePropertyChanged("AltinnErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AltinnExtendedErrorMessage {
            get {
                return this.AltinnExtendedErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.AltinnExtendedErrorMessageField, value) != true)) {
                    this.AltinnExtendedErrorMessageField = value;
                    this.RaisePropertyChanged("AltinnExtendedErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AltinnLocalizedErrorMessage {
            get {
                return this.AltinnLocalizedErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.AltinnLocalizedErrorMessageField, value) != true)) {
                    this.AltinnLocalizedErrorMessageField = value;
                    this.RaisePropertyChanged("AltinnLocalizedErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorGuid {
            get {
                return this.ErrorGuidField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorGuidField, value) != true)) {
                    this.ErrorGuidField = value;
                    this.RaisePropertyChanged("ErrorGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorID {
            get {
                return this.ErrorIDField;
            }
            set {
                if ((this.ErrorIDField.Equals(value) != true)) {
                    this.ErrorIDField = value;
                    this.RaisePropertyChanged("ErrorID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserGuid {
            get {
                return this.UserGuidField;
            }
            set {
                if ((object.ReferenceEquals(this.UserGuidField, value) != true)) {
                    this.UserGuidField = value;
                    this.RaisePropertyChanged("UserGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIdField, value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.altinn.no/services/Archive/ReporteeArchive/2013/06", ConfigurationName="ReporteeArchiveStreamedEC2.IReporteeArchiveExternalStreamedEC2")]
    public interface IReporteeArchiveExternalStreamedEC2 {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://www.altinn.no/services/2009/10) of message TestRequest does not match the default value (http://www.altinn.no/services/Archive/ReporteeArchive/2013/06)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/2009/10/IAltinnContractBase/Test", ReplyAction="http://www.altinn.no/services/2009/10/IAltinnContractBase/TestResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EC_Endpoint_Client.ReporteeArchiveStreamedEC2.AltinnFault), Action="http://www.altinn.no/services/2009/10/IAltinnContractBase/TestAltinnFaultFault", Name="AltinnFault", Namespace="http://www.altinn.no/services/common/fault/2009/10")]
        EC_Endpoint_Client.ReporteeArchiveStreamedEC2.TestResponse Test(EC_Endpoint_Client.ReporteeArchiveStreamedEC2.TestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/2009/10/IAltinnContractBase/Test", ReplyAction="http://www.altinn.no/services/2009/10/IAltinnContractBase/TestResponse")]
        System.Threading.Tasks.Task<EC_Endpoint_Client.ReporteeArchiveStreamedEC2.TestResponse> TestAsync(EC_Endpoint_Client.ReporteeArchiveStreamedEC2.TestRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace http://www.altinn.no/services/Archive/ReporteeArchive/2013/06 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/Archive/ReporteeArchive/2013/06/IReporteeArchiveExt" +
            "ernalStreamedEC/GetAttachmentDataECStreamed", ReplyAction="http://www.altinn.no/services/Archive/ReporteeArchive/2013/06/IReporteeArchiveExt" +
            "ernalStreamedEC/GetAttachmentDataECStreamedResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EC_Endpoint_Client.ReporteeArchiveStreamedEC2.AltinnFault), Action="http://www.altinn.no/services/Archive/ReporteeArchive/2013/06/IReporteeArchiveExt" +
            "ernalStreamedEC/GetAttachmentDataECStreamedAltinnFaultFault", Name="AltinnFault", Namespace="http://www.altinn.no/services/common/fault/2009/10")]
        EC_Endpoint_Client.ReporteeArchiveStreamedEC2.GetAttachmentDataECStreamedResponse GetAttachmentDataECStreamed(EC_Endpoint_Client.ReporteeArchiveStreamedEC2.GetAttachmentDataECStreamedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/Archive/ReporteeArchive/2013/06/IReporteeArchiveExt" +
            "ernalStreamedEC/GetAttachmentDataECStreamed", ReplyAction="http://www.altinn.no/services/Archive/ReporteeArchive/2013/06/IReporteeArchiveExt" +
            "ernalStreamedEC/GetAttachmentDataECStreamedResponse")]
        System.Threading.Tasks.Task<EC_Endpoint_Client.ReporteeArchiveStreamedEC2.GetAttachmentDataECStreamedResponse> GetAttachmentDataECStreamedAsync(EC_Endpoint_Client.ReporteeArchiveStreamedEC2.GetAttachmentDataECStreamedRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Test", WrapperNamespace="http://www.altinn.no/services/2009/10", IsWrapped=true)]
    public partial class TestRequest {
        
        public TestRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TestResponse", WrapperNamespace="http://www.altinn.no/services/2009/10", IsWrapped=true)]
    public partial class TestResponse {
        
        public TestResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAttachmentDataECStreamedRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAttachmentDataECStreamed", Namespace="http://www.altinn.no/services/Archive/ReporteeArchive/2013/06", Order=0)]
        public EC_Endpoint_Client.ReporteeArchiveStreamedEC2.GetAttachmentDataECStreamedRequestBody Body;
        
        public GetAttachmentDataECStreamedRequest() {
        }
        
        public GetAttachmentDataECStreamedRequest(EC_Endpoint_Client.ReporteeArchiveStreamedEC2.GetAttachmentDataECStreamedRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.altinn.no/services/Archive/ReporteeArchive/2013/06")]
    public partial class GetAttachmentDataECStreamedRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int attachmentId;
        
        public GetAttachmentDataECStreamedRequestBody() {
        }
        
        public GetAttachmentDataECStreamedRequestBody(string userName, string password, int attachmentId) {
            this.userName = userName;
            this.password = password;
            this.attachmentId = attachmentId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAttachmentDataECStreamedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAttachmentDataECStreamedResponse", Namespace="http://www.altinn.no/services/Archive/ReporteeArchive/2013/06", Order=0)]
        public EC_Endpoint_Client.ReporteeArchiveStreamedEC2.GetAttachmentDataECStreamedResponseBody Body;
        
        public GetAttachmentDataECStreamedResponse() {
        }
        
        public GetAttachmentDataECStreamedResponse(EC_Endpoint_Client.ReporteeArchiveStreamedEC2.GetAttachmentDataECStreamedResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.altinn.no/services/Archive/ReporteeArchive/2013/06")]
    public partial class GetAttachmentDataECStreamedResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public byte[] GetAttachmentDataECStreamedResult;
        
        public GetAttachmentDataECStreamedResponseBody() {
        }
        
        public GetAttachmentDataECStreamedResponseBody(byte[] GetAttachmentDataECStreamedResult) {
            this.GetAttachmentDataECStreamedResult = GetAttachmentDataECStreamedResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReporteeArchiveExternalStreamedEC2Channel : EC_Endpoint_Client.ReporteeArchiveStreamedEC2.IReporteeArchiveExternalStreamedEC2, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReporteeArchiveExternalStreamedEC2Client : System.ServiceModel.ClientBase<EC_Endpoint_Client.ReporteeArchiveStreamedEC2.IReporteeArchiveExternalStreamedEC2>, EC_Endpoint_Client.ReporteeArchiveStreamedEC2.IReporteeArchiveExternalStreamedEC2 {
        
        public ReporteeArchiveExternalStreamedEC2Client() {
        }
        
        public ReporteeArchiveExternalStreamedEC2Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReporteeArchiveExternalStreamedEC2Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReporteeArchiveExternalStreamedEC2Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReporteeArchiveExternalStreamedEC2Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EC_Endpoint_Client.ReporteeArchiveStreamedEC2.TestResponse EC_Endpoint_Client.ReporteeArchiveStreamedEC2.IReporteeArchiveExternalStreamedEC2.Test(EC_Endpoint_Client.ReporteeArchiveStreamedEC2.TestRequest request) {
            return base.Channel.Test(request);
        }
        
        public void Test() {
            EC_Endpoint_Client.ReporteeArchiveStreamedEC2.TestRequest inValue = new EC_Endpoint_Client.ReporteeArchiveStreamedEC2.TestRequest();
            EC_Endpoint_Client.ReporteeArchiveStreamedEC2.TestResponse retVal = ((EC_Endpoint_Client.ReporteeArchiveStreamedEC2.IReporteeArchiveExternalStreamedEC2)(this)).Test(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EC_Endpoint_Client.ReporteeArchiveStreamedEC2.TestResponse> EC_Endpoint_Client.ReporteeArchiveStreamedEC2.IReporteeArchiveExternalStreamedEC2.TestAsync(EC_Endpoint_Client.ReporteeArchiveStreamedEC2.TestRequest request) {
            return base.Channel.TestAsync(request);
        }
        
        public System.Threading.Tasks.Task<EC_Endpoint_Client.ReporteeArchiveStreamedEC2.TestResponse> TestAsync() {
            EC_Endpoint_Client.ReporteeArchiveStreamedEC2.TestRequest inValue = new EC_Endpoint_Client.ReporteeArchiveStreamedEC2.TestRequest();
            return ((EC_Endpoint_Client.ReporteeArchiveStreamedEC2.IReporteeArchiveExternalStreamedEC2)(this)).TestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EC_Endpoint_Client.ReporteeArchiveStreamedEC2.GetAttachmentDataECStreamedResponse EC_Endpoint_Client.ReporteeArchiveStreamedEC2.IReporteeArchiveExternalStreamedEC2.GetAttachmentDataECStreamed(EC_Endpoint_Client.ReporteeArchiveStreamedEC2.GetAttachmentDataECStreamedRequest request) {
            return base.Channel.GetAttachmentDataECStreamed(request);
        }
        
        public byte[] GetAttachmentDataECStreamed(string userName, string password, int attachmentId) {
            EC_Endpoint_Client.ReporteeArchiveStreamedEC2.GetAttachmentDataECStreamedRequest inValue = new EC_Endpoint_Client.ReporteeArchiveStreamedEC2.GetAttachmentDataECStreamedRequest();
            inValue.Body = new EC_Endpoint_Client.ReporteeArchiveStreamedEC2.GetAttachmentDataECStreamedRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.attachmentId = attachmentId;
            EC_Endpoint_Client.ReporteeArchiveStreamedEC2.GetAttachmentDataECStreamedResponse retVal = ((EC_Endpoint_Client.ReporteeArchiveStreamedEC2.IReporteeArchiveExternalStreamedEC2)(this)).GetAttachmentDataECStreamed(inValue);
            return retVal.Body.GetAttachmentDataECStreamedResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EC_Endpoint_Client.ReporteeArchiveStreamedEC2.GetAttachmentDataECStreamedResponse> EC_Endpoint_Client.ReporteeArchiveStreamedEC2.IReporteeArchiveExternalStreamedEC2.GetAttachmentDataECStreamedAsync(EC_Endpoint_Client.ReporteeArchiveStreamedEC2.GetAttachmentDataECStreamedRequest request) {
            return base.Channel.GetAttachmentDataECStreamedAsync(request);
        }
        
        public System.Threading.Tasks.Task<EC_Endpoint_Client.ReporteeArchiveStreamedEC2.GetAttachmentDataECStreamedResponse> GetAttachmentDataECStreamedAsync(string userName, string password, int attachmentId) {
            EC_Endpoint_Client.ReporteeArchiveStreamedEC2.GetAttachmentDataECStreamedRequest inValue = new EC_Endpoint_Client.ReporteeArchiveStreamedEC2.GetAttachmentDataECStreamedRequest();
            inValue.Body = new EC_Endpoint_Client.ReporteeArchiveStreamedEC2.GetAttachmentDataECStreamedRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.attachmentId = attachmentId;
            return ((EC_Endpoint_Client.ReporteeArchiveStreamedEC2.IReporteeArchiveExternalStreamedEC2)(this)).GetAttachmentDataECStreamedAsync(inValue);
        }
    }
}
