//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC_Endpoint_Client.NotificationAgency {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AltinnFault", Namespace="http://www.altinn.no/services/common/fault/2009/10")]
    [System.SerializableAttribute()]
    public partial class AltinnFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AltinnErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AltinnExtendedErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AltinnLocalizedErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AltinnErrorMessage {
            get {
                return this.AltinnErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.AltinnErrorMessageField, value) != true)) {
                    this.AltinnErrorMessageField = value;
                    this.RaisePropertyChanged("AltinnErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AltinnExtendedErrorMessage {
            get {
                return this.AltinnExtendedErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.AltinnExtendedErrorMessageField, value) != true)) {
                    this.AltinnExtendedErrorMessageField = value;
                    this.RaisePropertyChanged("AltinnExtendedErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AltinnLocalizedErrorMessage {
            get {
                return this.AltinnLocalizedErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.AltinnLocalizedErrorMessageField, value) != true)) {
                    this.AltinnLocalizedErrorMessageField = value;
                    this.RaisePropertyChanged("AltinnLocalizedErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorGuid {
            get {
                return this.ErrorGuidField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorGuidField, value) != true)) {
                    this.ErrorGuidField = value;
                    this.RaisePropertyChanged("ErrorGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorID {
            get {
                return this.ErrorIDField;
            }
            set {
                if ((this.ErrorIDField.Equals(value) != true)) {
                    this.ErrorIDField = value;
                    this.RaisePropertyChanged("ErrorID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserGuid {
            get {
                return this.UserGuidField;
            }
            set {
                if ((object.ReferenceEquals(this.UserGuidField, value) != true)) {
                    this.UserGuidField = value;
                    this.RaisePropertyChanged("UserGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIdField, value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="StandaloneNotificationBEList", Namespace="http://schemas.altinn.no/services/ServiceEngine/StandaloneNotificationBE/2009/10", ItemName="StandaloneNotification")]
    [System.SerializableAttribute()]
    public class StandaloneNotificationBEList : System.Collections.Generic.List<EC_Endpoint_Client.NotificationAgency.StandaloneNotification> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StandaloneNotification", Namespace="http://schemas.altinn.no/services/ServiceEngine/Notification/2009/10")]
    [System.SerializableAttribute()]
    public partial class StandaloneNotification : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        public StandaloneNotification()
        {
            this.TextTokens = new TextTokenSubstitutionBEList();
            this.ReceiverEndPoints = new ReceiverEndPointBEList();
        }
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FromAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LanguageIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NotificationTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EC_Endpoint_Client.NotificationAgency.ReceiverEndPointBEList ReceiverEndPointsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReporteeNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ShipmentDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EC_Endpoint_Client.NotificationAgency.TextTokenSubstitutionBEList TextTokensField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FromAddress {
            get {
                return this.FromAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.FromAddressField, value) != true)) {
                    this.FromAddressField = value;
                    this.RaisePropertyChanged("FromAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LanguageID {
            get {
                return this.LanguageIDField;
            }
            set {
                if ((this.LanguageIDField.Equals(value) != true)) {
                    this.LanguageIDField = value;
                    this.RaisePropertyChanged("LanguageID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NotificationType {
            get {
                return this.NotificationTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.NotificationTypeField, value) != true)) {
                    this.NotificationTypeField = value;
                    this.RaisePropertyChanged("NotificationType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EC_Endpoint_Client.NotificationAgency.ReceiverEndPointBEList ReceiverEndPoints {
            get {
                return this.ReceiverEndPointsField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiverEndPointsField, value) != true)) {
                    this.ReceiverEndPointsField = value;
                    this.RaisePropertyChanged("ReceiverEndPoints");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReporteeNumber {
            get {
                return this.ReporteeNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ReporteeNumberField, value) != true)) {
                    this.ReporteeNumberField = value;
                    this.RaisePropertyChanged("ReporteeNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ShipmentDateTime {
            get {
                return this.ShipmentDateTimeField;
            }
            set {
                if ((this.ShipmentDateTimeField.Equals(value) != true)) {
                    this.ShipmentDateTimeField = value;
                    this.RaisePropertyChanged("ShipmentDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EC_Endpoint_Client.NotificationAgency.TextTokenSubstitutionBEList TextTokens {
            get {
                return this.TextTokensField;
            }
            set {
                if ((object.ReferenceEquals(this.TextTokensField, value) != true)) {
                    this.TextTokensField = value;
                    this.RaisePropertyChanged("TextTokens");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ReceiverEndPointBEList", Namespace="http://schemas.altinn.no/services/ServiceEngine/Notification/2009/10", ItemName="ReceiverEndPoint")]
    [System.SerializableAttribute()]
    public class ReceiverEndPointBEList : System.Collections.Generic.List<EC_Endpoint_Client.NotificationAgency.ReceiverEndPoint> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="TextTokenSubstitutionBEList", Namespace="http://schemas.altinn.no/services/ServiceEngine/Notification/2009/10", ItemName="TextToken")]
    [System.SerializableAttribute()]
    public class TextTokenSubstitutionBEList : System.Collections.Generic.List<EC_Endpoint_Client.NotificationAgency.TextToken> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReceiverEndPoint", Namespace="http://schemas.altinn.no/services/ServiceEngine/Notification/2009/10")]
    [System.SerializableAttribute()]
    public partial class ReceiverEndPoint : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<EC_Endpoint_Client.NotificationAgency.TransportType> TransportTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiverAddressField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<EC_Endpoint_Client.NotificationAgency.TransportType> TransportType {
            get {
                return this.TransportTypeField;
            }
            set {
                if ((this.TransportTypeField.Equals(value) != true)) {
                    this.TransportTypeField = value;
                    this.RaisePropertyChanged("TransportType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string ReceiverAddress {
            get {
                return this.ReceiverAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiverAddressField, value) != true)) {
                    this.ReceiverAddressField = value;
                    this.RaisePropertyChanged("ReceiverAddress");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransportType", Namespace="http://schemas.altinn.no/serviceengine/formsengine/2009/10")]
    public enum TransportType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SMS = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Email = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IM = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Both = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TextToken", Namespace="http://schemas.altinn.no/services/ServiceEngine/Notification/2009/10")]
    [System.SerializableAttribute()]
    public partial class TextToken : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TokenNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TokenNum {
            get {
                return this.TokenNumField;
            }
            set {
                if ((this.TokenNumField.Equals(value) != true)) {
                    this.TokenNumField = value;
                    this.RaisePropertyChanged("TokenNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TokenValue {
            get {
                return this.TokenValueField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenValueField, value) != true)) {
                    this.TokenValueField = value;
                    this.RaisePropertyChanged("TokenValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.altinn.no/services/ServiceEngine/Notification/2010/10", ConfigurationName="NotificationAgency.INotificationAgencyExternalEC")]
    public interface INotificationAgencyExternalEC {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://www.altinn.no/services/2009/10) of message TestRequest does not match the default value (http://www.altinn.no/services/ServiceEngine/Notification/2010/10)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/2009/10/IAltinnContractBase/Test", ReplyAction="http://www.altinn.no/services/2009/10/IAltinnContractBase/TestResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EC_Endpoint_Client.NotificationAgency.AltinnFault), Action="http://www.altinn.no/services/2009/10/IAltinnContractBase/TestAltinnFaultFault", Name="AltinnFault", Namespace="http://www.altinn.no/services/common/fault/2009/10")]
        EC_Endpoint_Client.NotificationAgency.TestResponse Test(EC_Endpoint_Client.NotificationAgency.TestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/2009/10/IAltinnContractBase/Test", ReplyAction="http://www.altinn.no/services/2009/10/IAltinnContractBase/TestResponse")]
        System.Threading.Tasks.Task<EC_Endpoint_Client.NotificationAgency.TestResponse> TestAsync(EC_Endpoint_Client.NotificationAgency.TestRequest request);
        
        // CODEGEN: Generating message contract since element name systemUserName from namespace http://www.altinn.no/services/ServiceEngine/Notification/2010/10 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/ServiceEngine/Notification/2010/10/INotificationAge" +
            "ncyExternalEC/SendStandaloneNotificationEC", ReplyAction="http://www.altinn.no/services/ServiceEngine/Notification/2010/10/INotificationAge" +
            "ncyExternalEC/SendStandaloneNotificationECResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EC_Endpoint_Client.NotificationAgency.AltinnFault), Action="http://www.altinn.no/services/ServiceEngine/Notification/2010/10/INotificationAge" +
            "ncyExternalEC/SendStandaloneNotificationECAltinnFaultFault", Name="AltinnFault", Namespace="http://www.altinn.no/services/common/fault/2009/10")]
        EC_Endpoint_Client.NotificationAgency.SendStandaloneNotificationECResponse SendStandaloneNotificationEC(EC_Endpoint_Client.NotificationAgency.SendStandaloneNotificationECRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/ServiceEngine/Notification/2010/10/INotificationAge" +
            "ncyExternalEC/SendStandaloneNotificationEC", ReplyAction="http://www.altinn.no/services/ServiceEngine/Notification/2010/10/INotificationAge" +
            "ncyExternalEC/SendStandaloneNotificationECResponse")]
        System.Threading.Tasks.Task<EC_Endpoint_Client.NotificationAgency.SendStandaloneNotificationECResponse> SendStandaloneNotificationECAsync(EC_Endpoint_Client.NotificationAgency.SendStandaloneNotificationECRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Test", WrapperNamespace="http://www.altinn.no/services/2009/10", IsWrapped=true)]
    public partial class TestRequest {
        
        public TestRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TestResponse", WrapperNamespace="http://www.altinn.no/services/2009/10", IsWrapped=true)]
    public partial class TestResponse {
        
        public TestResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendStandaloneNotificationECRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendStandaloneNotificationEC", Namespace="http://www.altinn.no/services/ServiceEngine/Notification/2010/10", Order=0)]
        public EC_Endpoint_Client.NotificationAgency.SendStandaloneNotificationECRequestBody Body;
        
        public SendStandaloneNotificationECRequest() {
        }
        
        public SendStandaloneNotificationECRequest(EC_Endpoint_Client.NotificationAgency.SendStandaloneNotificationECRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.altinn.no/services/ServiceEngine/Notification/2010/10")]
    public partial class SendStandaloneNotificationECRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string systemUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string systemPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public EC_Endpoint_Client.NotificationAgency.StandaloneNotificationBEList standaloneNotifications;
        
        public SendStandaloneNotificationECRequestBody() {
        }
        
        public SendStandaloneNotificationECRequestBody(string systemUserName, string systemPassword, EC_Endpoint_Client.NotificationAgency.StandaloneNotificationBEList standaloneNotifications) {
            this.systemUserName = systemUserName;
            this.systemPassword = systemPassword;
            this.standaloneNotifications = standaloneNotifications;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendStandaloneNotificationECResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendStandaloneNotificationECResponse", Namespace="http://www.altinn.no/services/ServiceEngine/Notification/2010/10", Order=0)]
        public EC_Endpoint_Client.NotificationAgency.SendStandaloneNotificationECResponseBody Body;
        
        public SendStandaloneNotificationECResponse() {
        }
        
        public SendStandaloneNotificationECResponse(EC_Endpoint_Client.NotificationAgency.SendStandaloneNotificationECResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SendStandaloneNotificationECResponseBody {
        
        public SendStandaloneNotificationECResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INotificationAgencyExternalECChannel : EC_Endpoint_Client.NotificationAgency.INotificationAgencyExternalEC, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NotificationAgencyExternalECClient : System.ServiceModel.ClientBase<EC_Endpoint_Client.NotificationAgency.INotificationAgencyExternalEC>, EC_Endpoint_Client.NotificationAgency.INotificationAgencyExternalEC {
        
        public NotificationAgencyExternalECClient() {
        }
        
        public NotificationAgencyExternalECClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NotificationAgencyExternalECClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NotificationAgencyExternalECClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NotificationAgencyExternalECClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EC_Endpoint_Client.NotificationAgency.TestResponse EC_Endpoint_Client.NotificationAgency.INotificationAgencyExternalEC.Test(EC_Endpoint_Client.NotificationAgency.TestRequest request) {
            return base.Channel.Test(request);
        }
        
        public void Test() {
            EC_Endpoint_Client.NotificationAgency.TestRequest inValue = new EC_Endpoint_Client.NotificationAgency.TestRequest();
            EC_Endpoint_Client.NotificationAgency.TestResponse retVal = ((EC_Endpoint_Client.NotificationAgency.INotificationAgencyExternalEC)(this)).Test(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EC_Endpoint_Client.NotificationAgency.TestResponse> EC_Endpoint_Client.NotificationAgency.INotificationAgencyExternalEC.TestAsync(EC_Endpoint_Client.NotificationAgency.TestRequest request) {
            return base.Channel.TestAsync(request);
        }
        
        public System.Threading.Tasks.Task<EC_Endpoint_Client.NotificationAgency.TestResponse> TestAsync() {
            EC_Endpoint_Client.NotificationAgency.TestRequest inValue = new EC_Endpoint_Client.NotificationAgency.TestRequest();
            return ((EC_Endpoint_Client.NotificationAgency.INotificationAgencyExternalEC)(this)).TestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EC_Endpoint_Client.NotificationAgency.SendStandaloneNotificationECResponse EC_Endpoint_Client.NotificationAgency.INotificationAgencyExternalEC.SendStandaloneNotificationEC(EC_Endpoint_Client.NotificationAgency.SendStandaloneNotificationECRequest request) {
            return base.Channel.SendStandaloneNotificationEC(request);
        }
        
        public void SendStandaloneNotificationEC(string systemUserName, string systemPassword, EC_Endpoint_Client.NotificationAgency.StandaloneNotificationBEList standaloneNotifications) {
            EC_Endpoint_Client.NotificationAgency.SendStandaloneNotificationECRequest inValue = new EC_Endpoint_Client.NotificationAgency.SendStandaloneNotificationECRequest();
            inValue.Body = new EC_Endpoint_Client.NotificationAgency.SendStandaloneNotificationECRequestBody();
            inValue.Body.systemUserName = systemUserName;
            inValue.Body.systemPassword = systemPassword;
            inValue.Body.standaloneNotifications = standaloneNotifications;
            EC_Endpoint_Client.NotificationAgency.SendStandaloneNotificationECResponse retVal = ((EC_Endpoint_Client.NotificationAgency.INotificationAgencyExternalEC)(this)).SendStandaloneNotificationEC(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EC_Endpoint_Client.NotificationAgency.SendStandaloneNotificationECResponse> EC_Endpoint_Client.NotificationAgency.INotificationAgencyExternalEC.SendStandaloneNotificationECAsync(EC_Endpoint_Client.NotificationAgency.SendStandaloneNotificationECRequest request) {
            return base.Channel.SendStandaloneNotificationECAsync(request);
        }
        
        public System.Threading.Tasks.Task<EC_Endpoint_Client.NotificationAgency.SendStandaloneNotificationECResponse> SendStandaloneNotificationECAsync(string systemUserName, string systemPassword, EC_Endpoint_Client.NotificationAgency.StandaloneNotificationBEList standaloneNotifications) {
            EC_Endpoint_Client.NotificationAgency.SendStandaloneNotificationECRequest inValue = new EC_Endpoint_Client.NotificationAgency.SendStandaloneNotificationECRequest();
            inValue.Body = new EC_Endpoint_Client.NotificationAgency.SendStandaloneNotificationECRequestBody();
            inValue.Body.systemUserName = systemUserName;
            inValue.Body.systemPassword = systemPassword;
            inValue.Body.standaloneNotifications = standaloneNotifications;
            return ((EC_Endpoint_Client.NotificationAgency.INotificationAgencyExternalEC)(this)).SendStandaloneNotificationECAsync(inValue);
        }
    }
}
