//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC_Endpoint_Client.BatchLoggingAgency {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AltinnFault", Namespace="http://www.altinn.no/services/common/fault/2009/10")]
    [System.SerializableAttribute()]
    public partial class AltinnFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AltinnErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AltinnExtendedErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AltinnLocalizedErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AltinnErrorMessage {
            get {
                return this.AltinnErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.AltinnErrorMessageField, value) != true)) {
                    this.AltinnErrorMessageField = value;
                    this.RaisePropertyChanged("AltinnErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AltinnExtendedErrorMessage {
            get {
                return this.AltinnExtendedErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.AltinnExtendedErrorMessageField, value) != true)) {
                    this.AltinnExtendedErrorMessageField = value;
                    this.RaisePropertyChanged("AltinnExtendedErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AltinnLocalizedErrorMessage {
            get {
                return this.AltinnLocalizedErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.AltinnLocalizedErrorMessageField, value) != true)) {
                    this.AltinnLocalizedErrorMessageField = value;
                    this.RaisePropertyChanged("AltinnLocalizedErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorGuid {
            get {
                return this.ErrorGuidField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorGuidField, value) != true)) {
                    this.ErrorGuidField = value;
                    this.RaisePropertyChanged("ErrorGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorID {
            get {
                return this.ErrorIDField;
            }
            set {
                if ((this.ErrorIDField.Equals(value) != true)) {
                    this.ErrorIDField = value;
                    this.RaisePropertyChanged("ErrorID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserGuid {
            get {
                return this.UserGuidField;
            }
            set {
                if ((object.ReferenceEquals(this.UserGuidField, value) != true)) {
                    this.UserGuidField = value;
                    this.RaisePropertyChanged("UserGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIdField, value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BatchLoggingRequestExternal", Namespace="http://www.altinn.no/services/Intermediary/BatchLogging/2016/02")]
    [System.SerializableAttribute()]
    public partial class BatchLoggingRequestExternal : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> DataBatchIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<EC_Endpoint_Client.BatchLoggingAgency.DataBatchType> DataBatchTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> FromIssueIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SequenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SystemUserCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EC_Endpoint_Client.BatchLoggingAgency.BatchLoggingDateTimeRequestExternal TimeRangeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> DataBatchId {
            get {
                return this.DataBatchIdField;
            }
            set {
                if ((this.DataBatchIdField.Equals(value) != true)) {
                    this.DataBatchIdField = value;
                    this.RaisePropertyChanged("DataBatchId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<EC_Endpoint_Client.BatchLoggingAgency.DataBatchType> DataBatchType {
            get {
                return this.DataBatchTypeField;
            }
            set {
                if ((this.DataBatchTypeField.Equals(value) != true)) {
                    this.DataBatchTypeField = value;
                    this.RaisePropertyChanged("DataBatchType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> FromIssueId {
            get {
                return this.FromIssueIdField;
            }
            set {
                if ((this.FromIssueIdField.Equals(value) != true)) {
                    this.FromIssueIdField = value;
                    this.RaisePropertyChanged("FromIssueId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Sequence {
            get {
                return this.SequenceField;
            }
            set {
                if ((this.SequenceField.Equals(value) != true)) {
                    this.SequenceField = value;
                    this.RaisePropertyChanged("Sequence");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SystemUserCode {
            get {
                return this.SystemUserCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SystemUserCodeField, value) != true)) {
                    this.SystemUserCodeField = value;
                    this.RaisePropertyChanged("SystemUserCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EC_Endpoint_Client.BatchLoggingAgency.BatchLoggingDateTimeRequestExternal TimeRange {
            get {
                return this.TimeRangeField;
            }
            set {
                if ((object.ReferenceEquals(this.TimeRangeField, value) != true)) {
                    this.TimeRangeField = value;
                    this.RaisePropertyChanged("TimeRange");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BatchLoggingDateTimeRequestExternal", Namespace="http://www.altinn.no/services/Intermediary/BatchLogging/2016/02")]
    [System.SerializableAttribute()]
    public partial class BatchLoggingDateTimeRequestExternal : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime DateFromField;
        
        private System.DateTime DateToField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime DateFrom {
            get {
                return this.DateFromField;
            }
            set {
                if ((this.DateFromField.Equals(value) != true)) {
                    this.DateFromField = value;
                    this.RaisePropertyChanged("DateFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime DateTo {
            get {
                return this.DateToField;
            }
            set {
                if ((this.DateToField.Equals(value) != true)) {
                    this.DateToField = value;
                    this.RaisePropertyChanged("DateTo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataBatchType", Namespace="http://www.altinn.no/services/Intermediary/BatchLogging/2016/02")]
    public enum DataBatchType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ActivateSubscription = 100,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Notification = 101,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Correspondence = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PreFill = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegisterDSFProperty = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegisterDSFPropertyAdd = 23,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegisterDSFStreet = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegisterDSFStreetAdd = 24,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegisterDSFUser = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegisterER = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Subscription = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BatchLoggingStatusOverview", Namespace="http://www.altinn.no/services/Intermediary/BatchLogging/2016/02")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EC_Endpoint_Client.BatchLoggingAgency.BatchLoggingDetailedStatus))]
    public partial class BatchLoggingStatusOverview : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EC_Endpoint_Client.BatchLoggingAgency.DataBatch[] DataBatchesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberOfIssuesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EC_Endpoint_Client.BatchLoggingAgency.DataBatch[] DataBatches {
            get {
                return this.DataBatchesField;
            }
            set {
                if ((object.ReferenceEquals(this.DataBatchesField, value) != true)) {
                    this.DataBatchesField = value;
                    this.RaisePropertyChanged("DataBatches");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumberOfIssues {
            get {
                return this.NumberOfIssuesField;
            }
            set {
                if ((this.NumberOfIssuesField.Equals(value) != true)) {
                    this.NumberOfIssuesField = value;
                    this.RaisePropertyChanged("NumberOfIssues");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BatchLoggingDetailedStatus", Namespace="http://www.altinn.no/services/Intermediary/BatchLogging/2016/02")]
    [System.SerializableAttribute()]
    public partial class BatchLoggingDetailedStatus : EC_Endpoint_Client.BatchLoggingAgency.BatchLoggingStatusOverview {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EC_Endpoint_Client.BatchLoggingAgency.DataItem[] DataItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EC_Endpoint_Client.BatchLoggingAgency.IssueExternal[] IssuesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EC_Endpoint_Client.BatchLoggingAgency.DataItem[] DataItems {
            get {
                return this.DataItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.DataItemsField, value) != true)) {
                    this.DataItemsField = value;
                    this.RaisePropertyChanged("DataItems");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EC_Endpoint_Client.BatchLoggingAgency.IssueExternal[] Issues {
            get {
                return this.IssuesField;
            }
            set {
                if ((object.ReferenceEquals(this.IssuesField, value) != true)) {
                    this.IssuesField = value;
                    this.RaisePropertyChanged("Issues");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataBatch", Namespace="http://www.altinn.no/services/Intermediary/BatchLogging/2016/02")]
    [System.SerializableAttribute()]
    public partial class DataBatch : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long DataBatchIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> EndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberOfIssuesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SequenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ShipmentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> StartDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long DataBatchId {
            get {
                return this.DataBatchIdField;
            }
            set {
                if ((this.DataBatchIdField.Equals(value) != true)) {
                    this.DataBatchIdField = value;
                    this.RaisePropertyChanged("DataBatchId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((this.EndDateField.Equals(value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumberOfIssues {
            get {
                return this.NumberOfIssuesField;
            }
            set {
                if ((this.NumberOfIssuesField.Equals(value) != true)) {
                    this.NumberOfIssuesField = value;
                    this.RaisePropertyChanged("NumberOfIssues");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Sequence {
            get {
                return this.SequenceField;
            }
            set {
                if ((this.SequenceField.Equals(value) != true)) {
                    this.SequenceField = value;
                    this.RaisePropertyChanged("Sequence");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ShipmentId {
            get {
                return this.ShipmentIdField;
            }
            set {
                if ((this.ShipmentIdField.Equals(value) != true)) {
                    this.ShipmentIdField = value;
                    this.RaisePropertyChanged("ShipmentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataItem", Namespace="http://www.altinn.no/services/Intermediary/BatchLogging/2016/02")]
    [System.SerializableAttribute()]
    public partial class DataItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> DataBatchIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long DataItemIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PositionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ServiceEditionCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> DataBatchId {
            get {
                return this.DataBatchIdField;
            }
            set {
                if ((this.DataBatchIdField.Equals(value) != true)) {
                    this.DataBatchIdField = value;
                    this.RaisePropertyChanged("DataBatchId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long DataItemId {
            get {
                return this.DataItemIdField;
            }
            set {
                if ((this.DataItemIdField.Equals(value) != true)) {
                    this.DataItemIdField = value;
                    this.RaisePropertyChanged("DataItemId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Line {
            get {
                return this.LineField;
            }
            set {
                if ((this.LineField.Equals(value) != true)) {
                    this.LineField = value;
                    this.RaisePropertyChanged("Line");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Position {
            get {
                return this.PositionField;
            }
            set {
                if ((this.PositionField.Equals(value) != true)) {
                    this.PositionField = value;
                    this.RaisePropertyChanged("Position");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceCode {
            get {
                return this.ServiceCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceCodeField, value) != true)) {
                    this.ServiceCodeField = value;
                    this.RaisePropertyChanged("ServiceCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ServiceEditionCode {
            get {
                return this.ServiceEditionCodeField;
            }
            set {
                if ((this.ServiceEditionCodeField.Equals(value) != true)) {
                    this.ServiceEditionCodeField = value;
                    this.RaisePropertyChanged("ServiceEditionCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IssueExternal", Namespace="http://www.altinn.no/services/Intermediary/BatchLogging/2016/02")]
    [System.SerializableAttribute()]
    public partial class IssueExternal : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long DataBatchIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> DataItemIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ErrorDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EC_Endpoint_Client.BatchLoggingAgency.IssueTypeExternal IssueTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long DataBatchId {
            get {
                return this.DataBatchIdField;
            }
            set {
                if ((this.DataBatchIdField.Equals(value) != true)) {
                    this.DataBatchIdField = value;
                    this.RaisePropertyChanged("DataBatchId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> DataItemId {
            get {
                return this.DataItemIdField;
            }
            set {
                if ((this.DataItemIdField.Equals(value) != true)) {
                    this.DataItemIdField = value;
                    this.RaisePropertyChanged("DataItemId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ErrorDateTime {
            get {
                return this.ErrorDateTimeField;
            }
            set {
                if ((this.ErrorDateTimeField.Equals(value) != true)) {
                    this.ErrorDateTimeField = value;
                    this.RaisePropertyChanged("ErrorDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EC_Endpoint_Client.BatchLoggingAgency.IssueTypeExternal IssueType {
            get {
                return this.IssueTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.IssueTypeField, value) != true)) {
                    this.IssueTypeField = value;
                    this.RaisePropertyChanged("IssueType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IssueTypeExternal", Namespace="http://www.altinn.no/services/Intermediary/BatchLogging/2016/02")]
    [System.SerializableAttribute()]
    public partial class IssueTypeExternal : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EC_Endpoint_Client.BatchLoggingAgency.IssueTypeLevelExternal LevelField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EC_Endpoint_Client.BatchLoggingAgency.IssueTypeLevelExternal Level {
            get {
                return this.LevelField;
            }
            set {
                if ((this.LevelField.Equals(value) != true)) {
                    this.LevelField = value;
                    this.RaisePropertyChanged("Level");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IssueTypeLevelExternal", Namespace="http://www.altinn.no/services/Intermediary/BatchLogging/2016/02")]
    public enum IssueTypeLevelExternal : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Other = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Information = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Critical = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.altinn.no/services/Intermediary/BatchLogging/2016/02", ConfigurationName="BatchLoggingAgency.IBatchLoggingAgencyExternalEC")]
    public interface IBatchLoggingAgencyExternalEC {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://www.altinn.no/services/2009/10) of message TestRequest does not match the default value (http://www.altinn.no/services/Intermediary/BatchLogging/2016/02)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/2009/10/IAltinnContractBase/Test", ReplyAction="http://www.altinn.no/services/2009/10/IAltinnContractBase/TestResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EC_Endpoint_Client.BatchLoggingAgency.AltinnFault), Action="http://www.altinn.no/services/2009/10/IAltinnContractBase/TestAltinnFaultFault", Name="AltinnFault", Namespace="http://www.altinn.no/services/common/fault/2009/10")]
        EC_Endpoint_Client.BatchLoggingAgency.TestResponse Test(EC_Endpoint_Client.BatchLoggingAgency.TestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/2009/10/IAltinnContractBase/Test", ReplyAction="http://www.altinn.no/services/2009/10/IAltinnContractBase/TestResponse")]
        System.Threading.Tasks.Task<EC_Endpoint_Client.BatchLoggingAgency.TestResponse> TestAsync(EC_Endpoint_Client.BatchLoggingAgency.TestRequest request);
        
        // CODEGEN: Generating message contract since element name agencyUserName from namespace http://www.altinn.no/services/Intermediary/BatchLogging/2016/02 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/Intermediary/BatchLogging/2016/02/IBatchLoggingAgen" +
            "cyExternalEC/GetStatusOverview", ReplyAction="http://www.altinn.no/services/Intermediary/BatchLogging/2016/02/IBatchLoggingAgen" +
            "cyExternalEC/GetStatusOverviewResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EC_Endpoint_Client.BatchLoggingAgency.AltinnFault), Action="http://www.altinn.no/services/Intermediary/BatchLogging/2016/02/IBatchLoggingAgen" +
            "cyExternalEC/GetStatusOverviewAltinnFaultFault", Name="AltinnFault", Namespace="http://www.altinn.no/services/common/fault/2009/10")]
        EC_Endpoint_Client.BatchLoggingAgency.GetStatusOverviewResponse GetStatusOverview(EC_Endpoint_Client.BatchLoggingAgency.GetStatusOverviewRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/Intermediary/BatchLogging/2016/02/IBatchLoggingAgen" +
            "cyExternalEC/GetStatusOverview", ReplyAction="http://www.altinn.no/services/Intermediary/BatchLogging/2016/02/IBatchLoggingAgen" +
            "cyExternalEC/GetStatusOverviewResponse")]
        System.Threading.Tasks.Task<EC_Endpoint_Client.BatchLoggingAgency.GetStatusOverviewResponse> GetStatusOverviewAsync(EC_Endpoint_Client.BatchLoggingAgency.GetStatusOverviewRequest request);
        
        // CODEGEN: Generating message contract since element name agencyUserName from namespace http://www.altinn.no/services/Intermediary/BatchLogging/2016/02 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/Intermediary/BatchLogging/2016/02/IBatchLoggingAgen" +
            "cyExternalEC/GetDetailedStatus", ReplyAction="http://www.altinn.no/services/Intermediary/BatchLogging/2016/02/IBatchLoggingAgen" +
            "cyExternalEC/GetDetailedStatusResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EC_Endpoint_Client.BatchLoggingAgency.AltinnFault), Action="http://www.altinn.no/services/Intermediary/BatchLogging/2016/02/IBatchLoggingAgen" +
            "cyExternalEC/GetDetailedStatusAltinnFaultFault", Name="AltinnFault", Namespace="http://www.altinn.no/services/common/fault/2009/10")]
        EC_Endpoint_Client.BatchLoggingAgency.GetDetailedStatusResponse GetDetailedStatus(EC_Endpoint_Client.BatchLoggingAgency.GetDetailedStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/Intermediary/BatchLogging/2016/02/IBatchLoggingAgen" +
            "cyExternalEC/GetDetailedStatus", ReplyAction="http://www.altinn.no/services/Intermediary/BatchLogging/2016/02/IBatchLoggingAgen" +
            "cyExternalEC/GetDetailedStatusResponse")]
        System.Threading.Tasks.Task<EC_Endpoint_Client.BatchLoggingAgency.GetDetailedStatusResponse> GetDetailedStatusAsync(EC_Endpoint_Client.BatchLoggingAgency.GetDetailedStatusRequest request);
        
        // CODEGEN: Generating message contract since element name agencyUserName from namespace http://www.altinn.no/services/Intermediary/BatchLogging/2016/02 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/Intermediary/BatchLogging/2016/02/IBatchLoggingAgen" +
            "cyExternalEC/GetDataItem", ReplyAction="http://www.altinn.no/services/Intermediary/BatchLogging/2016/02/IBatchLoggingAgen" +
            "cyExternalEC/GetDataItemResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EC_Endpoint_Client.BatchLoggingAgency.AltinnFault), Action="http://www.altinn.no/services/Intermediary/BatchLogging/2016/02/IBatchLoggingAgen" +
            "cyExternalEC/GetDataItemAltinnFaultFault", Name="AltinnFault", Namespace="http://www.altinn.no/services/common/fault/2009/10")]
        EC_Endpoint_Client.BatchLoggingAgency.GetDataItemResponse GetDataItem(EC_Endpoint_Client.BatchLoggingAgency.GetDataItemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/Intermediary/BatchLogging/2016/02/IBatchLoggingAgen" +
            "cyExternalEC/GetDataItem", ReplyAction="http://www.altinn.no/services/Intermediary/BatchLogging/2016/02/IBatchLoggingAgen" +
            "cyExternalEC/GetDataItemResponse")]
        System.Threading.Tasks.Task<EC_Endpoint_Client.BatchLoggingAgency.GetDataItemResponse> GetDataItemAsync(EC_Endpoint_Client.BatchLoggingAgency.GetDataItemRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Test", WrapperNamespace="http://www.altinn.no/services/2009/10", IsWrapped=true)]
    public partial class TestRequest {
        
        public TestRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TestResponse", WrapperNamespace="http://www.altinn.no/services/2009/10", IsWrapped=true)]
    public partial class TestResponse {
        
        public TestResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStatusOverviewRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStatusOverview", Namespace="http://www.altinn.no/services/Intermediary/BatchLogging/2016/02", Order=0)]
        public EC_Endpoint_Client.BatchLoggingAgency.GetStatusOverviewRequestBody Body;
        
        public GetStatusOverviewRequest() {
        }
        
        public GetStatusOverviewRequest(EC_Endpoint_Client.BatchLoggingAgency.GetStatusOverviewRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.altinn.no/services/Intermediary/BatchLogging/2016/02")]
    public partial class GetStatusOverviewRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string agencyUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string agencyPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public EC_Endpoint_Client.BatchLoggingAgency.BatchLoggingRequestExternal request;
        
        public GetStatusOverviewRequestBody() {
        }
        
        public GetStatusOverviewRequestBody(string agencyUserName, string agencyPassword, EC_Endpoint_Client.BatchLoggingAgency.BatchLoggingRequestExternal request) {
            this.agencyUserName = agencyUserName;
            this.agencyPassword = agencyPassword;
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStatusOverviewResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStatusOverviewResponse", Namespace="http://www.altinn.no/services/Intermediary/BatchLogging/2016/02", Order=0)]
        public EC_Endpoint_Client.BatchLoggingAgency.GetStatusOverviewResponseBody Body;
        
        public GetStatusOverviewResponse() {
        }
        
        public GetStatusOverviewResponse(EC_Endpoint_Client.BatchLoggingAgency.GetStatusOverviewResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.altinn.no/services/Intermediary/BatchLogging/2016/02")]
    public partial class GetStatusOverviewResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public EC_Endpoint_Client.BatchLoggingAgency.BatchLoggingStatusOverview GetStatusOverviewResult;
        
        public GetStatusOverviewResponseBody() {
        }
        
        public GetStatusOverviewResponseBody(EC_Endpoint_Client.BatchLoggingAgency.BatchLoggingStatusOverview GetStatusOverviewResult) {
            this.GetStatusOverviewResult = GetStatusOverviewResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDetailedStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDetailedStatus", Namespace="http://www.altinn.no/services/Intermediary/BatchLogging/2016/02", Order=0)]
        public EC_Endpoint_Client.BatchLoggingAgency.GetDetailedStatusRequestBody Body;
        
        public GetDetailedStatusRequest() {
        }
        
        public GetDetailedStatusRequest(EC_Endpoint_Client.BatchLoggingAgency.GetDetailedStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.altinn.no/services/Intermediary/BatchLogging/2016/02")]
    public partial class GetDetailedStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string agencyUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string agencyPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public EC_Endpoint_Client.BatchLoggingAgency.BatchLoggingRequestExternal request;
        
        public GetDetailedStatusRequestBody() {
        }
        
        public GetDetailedStatusRequestBody(string agencyUserName, string agencyPassword, EC_Endpoint_Client.BatchLoggingAgency.BatchLoggingRequestExternal request) {
            this.agencyUserName = agencyUserName;
            this.agencyPassword = agencyPassword;
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDetailedStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDetailedStatusResponse", Namespace="http://www.altinn.no/services/Intermediary/BatchLogging/2016/02", Order=0)]
        public EC_Endpoint_Client.BatchLoggingAgency.GetDetailedStatusResponseBody Body;
        
        public GetDetailedStatusResponse() {
        }
        
        public GetDetailedStatusResponse(EC_Endpoint_Client.BatchLoggingAgency.GetDetailedStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.altinn.no/services/Intermediary/BatchLogging/2016/02")]
    public partial class GetDetailedStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public EC_Endpoint_Client.BatchLoggingAgency.BatchLoggingDetailedStatus GetDetailedStatusResult;
        
        public GetDetailedStatusResponseBody() {
        }
        
        public GetDetailedStatusResponseBody(EC_Endpoint_Client.BatchLoggingAgency.BatchLoggingDetailedStatus GetDetailedStatusResult) {
            this.GetDetailedStatusResult = GetDetailedStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataItemRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataItem", Namespace="http://www.altinn.no/services/Intermediary/BatchLogging/2016/02", Order=0)]
        public EC_Endpoint_Client.BatchLoggingAgency.GetDataItemRequestBody Body;
        
        public GetDataItemRequest() {
        }
        
        public GetDataItemRequest(EC_Endpoint_Client.BatchLoggingAgency.GetDataItemRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.altinn.no/services/Intermediary/BatchLogging/2016/02")]
    public partial class GetDataItemRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string agencyUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string agencyPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long dataItemId;
        
        public GetDataItemRequestBody() {
        }
        
        public GetDataItemRequestBody(string agencyUserName, string agencyPassword, long dataItemId) {
            this.agencyUserName = agencyUserName;
            this.agencyPassword = agencyPassword;
            this.dataItemId = dataItemId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataItemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataItemResponse", Namespace="http://www.altinn.no/services/Intermediary/BatchLogging/2016/02", Order=0)]
        public EC_Endpoint_Client.BatchLoggingAgency.GetDataItemResponseBody Body;
        
        public GetDataItemResponse() {
        }
        
        public GetDataItemResponse(EC_Endpoint_Client.BatchLoggingAgency.GetDataItemResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.altinn.no/services/Intermediary/BatchLogging/2016/02")]
    public partial class GetDataItemResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public EC_Endpoint_Client.BatchLoggingAgency.DataItem GetDataItemResult;
        
        public GetDataItemResponseBody() {
        }
        
        public GetDataItemResponseBody(EC_Endpoint_Client.BatchLoggingAgency.DataItem GetDataItemResult) {
            this.GetDataItemResult = GetDataItemResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBatchLoggingAgencyExternalECChannel : EC_Endpoint_Client.BatchLoggingAgency.IBatchLoggingAgencyExternalEC, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BatchLoggingAgencyExternalECClient : System.ServiceModel.ClientBase<EC_Endpoint_Client.BatchLoggingAgency.IBatchLoggingAgencyExternalEC>, EC_Endpoint_Client.BatchLoggingAgency.IBatchLoggingAgencyExternalEC {
        
        public BatchLoggingAgencyExternalECClient() {
        }
        
        public BatchLoggingAgencyExternalECClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BatchLoggingAgencyExternalECClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BatchLoggingAgencyExternalECClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BatchLoggingAgencyExternalECClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EC_Endpoint_Client.BatchLoggingAgency.TestResponse EC_Endpoint_Client.BatchLoggingAgency.IBatchLoggingAgencyExternalEC.Test(EC_Endpoint_Client.BatchLoggingAgency.TestRequest request) {
            return base.Channel.Test(request);
        }
        
        public void Test() {
            EC_Endpoint_Client.BatchLoggingAgency.TestRequest inValue = new EC_Endpoint_Client.BatchLoggingAgency.TestRequest();
            EC_Endpoint_Client.BatchLoggingAgency.TestResponse retVal = ((EC_Endpoint_Client.BatchLoggingAgency.IBatchLoggingAgencyExternalEC)(this)).Test(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EC_Endpoint_Client.BatchLoggingAgency.TestResponse> EC_Endpoint_Client.BatchLoggingAgency.IBatchLoggingAgencyExternalEC.TestAsync(EC_Endpoint_Client.BatchLoggingAgency.TestRequest request) {
            return base.Channel.TestAsync(request);
        }
        
        public System.Threading.Tasks.Task<EC_Endpoint_Client.BatchLoggingAgency.TestResponse> TestAsync() {
            EC_Endpoint_Client.BatchLoggingAgency.TestRequest inValue = new EC_Endpoint_Client.BatchLoggingAgency.TestRequest();
            return ((EC_Endpoint_Client.BatchLoggingAgency.IBatchLoggingAgencyExternalEC)(this)).TestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EC_Endpoint_Client.BatchLoggingAgency.GetStatusOverviewResponse EC_Endpoint_Client.BatchLoggingAgency.IBatchLoggingAgencyExternalEC.GetStatusOverview(EC_Endpoint_Client.BatchLoggingAgency.GetStatusOverviewRequest request) {
            return base.Channel.GetStatusOverview(request);
        }
        
        public EC_Endpoint_Client.BatchLoggingAgency.BatchLoggingStatusOverview GetStatusOverview(string agencyUserName, string agencyPassword, EC_Endpoint_Client.BatchLoggingAgency.BatchLoggingRequestExternal request) {
            EC_Endpoint_Client.BatchLoggingAgency.GetStatusOverviewRequest inValue = new EC_Endpoint_Client.BatchLoggingAgency.GetStatusOverviewRequest();
            inValue.Body = new EC_Endpoint_Client.BatchLoggingAgency.GetStatusOverviewRequestBody();
            inValue.Body.agencyUserName = agencyUserName;
            inValue.Body.agencyPassword = agencyPassword;
            inValue.Body.request = request;
            EC_Endpoint_Client.BatchLoggingAgency.GetStatusOverviewResponse retVal = ((EC_Endpoint_Client.BatchLoggingAgency.IBatchLoggingAgencyExternalEC)(this)).GetStatusOverview(inValue);
            return retVal.Body.GetStatusOverviewResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EC_Endpoint_Client.BatchLoggingAgency.GetStatusOverviewResponse> EC_Endpoint_Client.BatchLoggingAgency.IBatchLoggingAgencyExternalEC.GetStatusOverviewAsync(EC_Endpoint_Client.BatchLoggingAgency.GetStatusOverviewRequest request) {
            return base.Channel.GetStatusOverviewAsync(request);
        }
        
        public System.Threading.Tasks.Task<EC_Endpoint_Client.BatchLoggingAgency.GetStatusOverviewResponse> GetStatusOverviewAsync(string agencyUserName, string agencyPassword, EC_Endpoint_Client.BatchLoggingAgency.BatchLoggingRequestExternal request) {
            EC_Endpoint_Client.BatchLoggingAgency.GetStatusOverviewRequest inValue = new EC_Endpoint_Client.BatchLoggingAgency.GetStatusOverviewRequest();
            inValue.Body = new EC_Endpoint_Client.BatchLoggingAgency.GetStatusOverviewRequestBody();
            inValue.Body.agencyUserName = agencyUserName;
            inValue.Body.agencyPassword = agencyPassword;
            inValue.Body.request = request;
            return ((EC_Endpoint_Client.BatchLoggingAgency.IBatchLoggingAgencyExternalEC)(this)).GetStatusOverviewAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EC_Endpoint_Client.BatchLoggingAgency.GetDetailedStatusResponse EC_Endpoint_Client.BatchLoggingAgency.IBatchLoggingAgencyExternalEC.GetDetailedStatus(EC_Endpoint_Client.BatchLoggingAgency.GetDetailedStatusRequest request) {
            return base.Channel.GetDetailedStatus(request);
        }
        
        public EC_Endpoint_Client.BatchLoggingAgency.BatchLoggingDetailedStatus GetDetailedStatus(string agencyUserName, string agencyPassword, EC_Endpoint_Client.BatchLoggingAgency.BatchLoggingRequestExternal request) {
            EC_Endpoint_Client.BatchLoggingAgency.GetDetailedStatusRequest inValue = new EC_Endpoint_Client.BatchLoggingAgency.GetDetailedStatusRequest();
            inValue.Body = new EC_Endpoint_Client.BatchLoggingAgency.GetDetailedStatusRequestBody();
            inValue.Body.agencyUserName = agencyUserName;
            inValue.Body.agencyPassword = agencyPassword;
            inValue.Body.request = request;
            EC_Endpoint_Client.BatchLoggingAgency.GetDetailedStatusResponse retVal = ((EC_Endpoint_Client.BatchLoggingAgency.IBatchLoggingAgencyExternalEC)(this)).GetDetailedStatus(inValue);
            return retVal.Body.GetDetailedStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EC_Endpoint_Client.BatchLoggingAgency.GetDetailedStatusResponse> EC_Endpoint_Client.BatchLoggingAgency.IBatchLoggingAgencyExternalEC.GetDetailedStatusAsync(EC_Endpoint_Client.BatchLoggingAgency.GetDetailedStatusRequest request) {
            return base.Channel.GetDetailedStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<EC_Endpoint_Client.BatchLoggingAgency.GetDetailedStatusResponse> GetDetailedStatusAsync(string agencyUserName, string agencyPassword, EC_Endpoint_Client.BatchLoggingAgency.BatchLoggingRequestExternal request) {
            EC_Endpoint_Client.BatchLoggingAgency.GetDetailedStatusRequest inValue = new EC_Endpoint_Client.BatchLoggingAgency.GetDetailedStatusRequest();
            inValue.Body = new EC_Endpoint_Client.BatchLoggingAgency.GetDetailedStatusRequestBody();
            inValue.Body.agencyUserName = agencyUserName;
            inValue.Body.agencyPassword = agencyPassword;
            inValue.Body.request = request;
            return ((EC_Endpoint_Client.BatchLoggingAgency.IBatchLoggingAgencyExternalEC)(this)).GetDetailedStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EC_Endpoint_Client.BatchLoggingAgency.GetDataItemResponse EC_Endpoint_Client.BatchLoggingAgency.IBatchLoggingAgencyExternalEC.GetDataItem(EC_Endpoint_Client.BatchLoggingAgency.GetDataItemRequest request) {
            return base.Channel.GetDataItem(request);
        }
        
        public EC_Endpoint_Client.BatchLoggingAgency.DataItem GetDataItem(string agencyUserName, string agencyPassword, long dataItemId) {
            EC_Endpoint_Client.BatchLoggingAgency.GetDataItemRequest inValue = new EC_Endpoint_Client.BatchLoggingAgency.GetDataItemRequest();
            inValue.Body = new EC_Endpoint_Client.BatchLoggingAgency.GetDataItemRequestBody();
            inValue.Body.agencyUserName = agencyUserName;
            inValue.Body.agencyPassword = agencyPassword;
            inValue.Body.dataItemId = dataItemId;
            EC_Endpoint_Client.BatchLoggingAgency.GetDataItemResponse retVal = ((EC_Endpoint_Client.BatchLoggingAgency.IBatchLoggingAgencyExternalEC)(this)).GetDataItem(inValue);
            return retVal.Body.GetDataItemResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EC_Endpoint_Client.BatchLoggingAgency.GetDataItemResponse> EC_Endpoint_Client.BatchLoggingAgency.IBatchLoggingAgencyExternalEC.GetDataItemAsync(EC_Endpoint_Client.BatchLoggingAgency.GetDataItemRequest request) {
            return base.Channel.GetDataItemAsync(request);
        }
        
        public System.Threading.Tasks.Task<EC_Endpoint_Client.BatchLoggingAgency.GetDataItemResponse> GetDataItemAsync(string agencyUserName, string agencyPassword, long dataItemId) {
            EC_Endpoint_Client.BatchLoggingAgency.GetDataItemRequest inValue = new EC_Endpoint_Client.BatchLoggingAgency.GetDataItemRequest();
            inValue.Body = new EC_Endpoint_Client.BatchLoggingAgency.GetDataItemRequestBody();
            inValue.Body.agencyUserName = agencyUserName;
            inValue.Body.agencyPassword = agencyPassword;
            inValue.Body.dataItemId = dataItemId;
            return ((EC_Endpoint_Client.BatchLoggingAgency.IBatchLoggingAgencyExternalEC)(this)).GetDataItemAsync(inValue);
        }
    }
}
