//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC_Endpoint_Client.SOArchive {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AltinnFault", Namespace="http://www.altinn.no/services/common/fault/2009/10")]
    [System.SerializableAttribute()]
    public partial class AltinnFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AltinnErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AltinnExtendedErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AltinnLocalizedErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AltinnErrorMessage {
            get {
                return this.AltinnErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.AltinnErrorMessageField, value) != true)) {
                    this.AltinnErrorMessageField = value;
                    this.RaisePropertyChanged("AltinnErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AltinnExtendedErrorMessage {
            get {
                return this.AltinnExtendedErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.AltinnExtendedErrorMessageField, value) != true)) {
                    this.AltinnExtendedErrorMessageField = value;
                    this.RaisePropertyChanged("AltinnExtendedErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AltinnLocalizedErrorMessage {
            get {
                return this.AltinnLocalizedErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.AltinnLocalizedErrorMessageField, value) != true)) {
                    this.AltinnLocalizedErrorMessageField = value;
                    this.RaisePropertyChanged("AltinnLocalizedErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorGuid {
            get {
                return this.ErrorGuidField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorGuidField, value) != true)) {
                    this.ErrorGuidField = value;
                    this.RaisePropertyChanged("ErrorGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorID {
            get {
                return this.ErrorIDField;
            }
            set {
                if ((this.ErrorIDField.Equals(value) != true)) {
                    this.ErrorIDField = value;
                    this.RaisePropertyChanged("ErrorID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserGuid {
            get {
                return this.UserGuidField;
            }
            set {
                if ((object.ReferenceEquals(this.UserGuidField, value) != true)) {
                    this.UserGuidField = value;
                    this.RaisePropertyChanged("UserGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIdField, value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArchivedFormTaskV2", Namespace="http://schemas.altinn.no/services/Archive/ReporteeArchive/2010/10")]
    [System.SerializableAttribute()]
    public partial class ArchivedFormTaskV2 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EC_Endpoint_Client.SOArchive.ArchiveTaskBEV2List ArchiveTaskListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EC_Endpoint_Client.SOArchive.ArchivedAttachmentBEV2List ArchivedAttachmentListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ArchivedDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EC_Endpoint_Client.SOArchive.ArchivedFormBEList ArchivedFormListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EC_Endpoint_Client.SOArchive.ArchivedFormTaskSigningStepBEV2List ArchivedFormTaskSigningStepListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExternalServiceCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ExternalServiceEditionCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double InvoiceInformationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastChangedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EC_Endpoint_Client.SOArchive.KeyExternalBE PasswordEncryptedSymmetricKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReporteeElementIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReporteeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EC_Endpoint_Client.SOArchive.KeyExternalBE SOEncryptedSymmetricdKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceOwnerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ssnOrgNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EC_Endpoint_Client.SOArchive.ArchiveTaskBEV2List ArchiveTaskList {
            get {
                return this.ArchiveTaskListField;
            }
            set {
                if ((object.ReferenceEquals(this.ArchiveTaskListField, value) != true)) {
                    this.ArchiveTaskListField = value;
                    this.RaisePropertyChanged("ArchiveTaskList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EC_Endpoint_Client.SOArchive.ArchivedAttachmentBEV2List ArchivedAttachmentList {
            get {
                return this.ArchivedAttachmentListField;
            }
            set {
                if ((object.ReferenceEquals(this.ArchivedAttachmentListField, value) != true)) {
                    this.ArchivedAttachmentListField = value;
                    this.RaisePropertyChanged("ArchivedAttachmentList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ArchivedDateTime {
            get {
                return this.ArchivedDateTimeField;
            }
            set {
                if ((this.ArchivedDateTimeField.Equals(value) != true)) {
                    this.ArchivedDateTimeField = value;
                    this.RaisePropertyChanged("ArchivedDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EC_Endpoint_Client.SOArchive.ArchivedFormBEList ArchivedFormList {
            get {
                return this.ArchivedFormListField;
            }
            set {
                if ((object.ReferenceEquals(this.ArchivedFormListField, value) != true)) {
                    this.ArchivedFormListField = value;
                    this.RaisePropertyChanged("ArchivedFormList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EC_Endpoint_Client.SOArchive.ArchivedFormTaskSigningStepBEV2List ArchivedFormTaskSigningStepList {
            get {
                return this.ArchivedFormTaskSigningStepListField;
            }
            set {
                if ((object.ReferenceEquals(this.ArchivedFormTaskSigningStepListField, value) != true)) {
                    this.ArchivedFormTaskSigningStepListField = value;
                    this.RaisePropertyChanged("ArchivedFormTaskSigningStepList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExternalServiceCode {
            get {
                return this.ExternalServiceCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ExternalServiceCodeField, value) != true)) {
                    this.ExternalServiceCodeField = value;
                    this.RaisePropertyChanged("ExternalServiceCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ExternalServiceEditionCode {
            get {
                return this.ExternalServiceEditionCodeField;
            }
            set {
                if ((this.ExternalServiceEditionCodeField.Equals(value) != true)) {
                    this.ExternalServiceEditionCodeField = value;
                    this.RaisePropertyChanged("ExternalServiceEditionCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double InvoiceInformation {
            get {
                return this.InvoiceInformationField;
            }
            set {
                if ((this.InvoiceInformationField.Equals(value) != true)) {
                    this.InvoiceInformationField = value;
                    this.RaisePropertyChanged("InvoiceInformation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastChanged {
            get {
                return this.LastChangedField;
            }
            set {
                if ((this.LastChangedField.Equals(value) != true)) {
                    this.LastChangedField = value;
                    this.RaisePropertyChanged("LastChanged");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EC_Endpoint_Client.SOArchive.KeyExternalBE PasswordEncryptedSymmetricKey {
            get {
                return this.PasswordEncryptedSymmetricKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordEncryptedSymmetricKeyField, value) != true)) {
                    this.PasswordEncryptedSymmetricKeyField = value;
                    this.RaisePropertyChanged("PasswordEncryptedSymmetricKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReporteeElementID {
            get {
                return this.ReporteeElementIDField;
            }
            set {
                if ((this.ReporteeElementIDField.Equals(value) != true)) {
                    this.ReporteeElementIDField = value;
                    this.RaisePropertyChanged("ReporteeElementID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReporteeID {
            get {
                return this.ReporteeIDField;
            }
            set {
                if ((this.ReporteeIDField.Equals(value) != true)) {
                    this.ReporteeIDField = value;
                    this.RaisePropertyChanged("ReporteeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EC_Endpoint_Client.SOArchive.KeyExternalBE SOEncryptedSymmetricdKey {
            get {
                return this.SOEncryptedSymmetricdKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.SOEncryptedSymmetricdKeyField, value) != true)) {
                    this.SOEncryptedSymmetricdKeyField = value;
                    this.RaisePropertyChanged("SOEncryptedSymmetricdKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceOwner {
            get {
                return this.ServiceOwnerField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceOwnerField, value) != true)) {
                    this.ServiceOwnerField = value;
                    this.RaisePropertyChanged("ServiceOwner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ssnOrgNumber {
            get {
                return this.ssnOrgNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ssnOrgNumberField, value) != true)) {
                    this.ssnOrgNumberField = value;
                    this.RaisePropertyChanged("ssnOrgNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KeyExternalBE", Namespace="http://schemas.altinn.no/services/Archive/KeyManagement/2010/10")]
    [System.SerializableAttribute()]
    public partial class KeyExternalBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CertificateThumbprintField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KeyIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CertificateThumbprint {
            get {
                return this.CertificateThumbprintField;
            }
            set {
                if ((object.ReferenceEquals(this.CertificateThumbprintField, value) != true)) {
                    this.CertificateThumbprintField = value;
                    this.RaisePropertyChanged("CertificateThumbprint");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int KeyID {
            get {
                return this.KeyIDField;
            }
            set {
                if ((this.KeyIDField.Equals(value) != true)) {
                    this.KeyIDField = value;
                    this.RaisePropertyChanged("KeyID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArchiveTaskBEV2List", Namespace="http://schemas.altinn.no/services/Archive/ReporteeArchive/2010/10", ItemName="ArchiveTaskV2")]
    [System.SerializableAttribute()]
    public class ArchiveTaskBEV2List : System.Collections.Generic.List<EC_Endpoint_Client.SOArchive.ArchiveTaskV2> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArchivedAttachmentBEV2List", Namespace="http://schemas.altinn.no/services/Archive/ReporteeArchive/2010/10", ItemName="ArchivedAttachmentBEV2")]
    [System.SerializableAttribute()]
    public class ArchivedAttachmentBEV2List : System.Collections.Generic.List<EC_Endpoint_Client.SOArchive.ArchivedAttachmentBEV2> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArchivedFormBEList", Namespace="http://schemas.altinn.no/services/Archive/ReporteeArchive/2009/10", ItemName="ArchivedFormBE")]
    [System.SerializableAttribute()]
    public class ArchivedFormBEList : System.Collections.Generic.List<EC_Endpoint_Client.SOArchive.ArchivedFormBE> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArchivedFormTaskSigningStepBEV2List", Namespace="http://schemas.altinn.no/services/Archive/ReporteeArchive/2010/10", ItemName="ArchivedFormTaskSigningStepBEV2")]
    [System.SerializableAttribute()]
    public class ArchivedFormTaskSigningStepBEV2List : System.Collections.Generic.List<EC_Endpoint_Client.SOArchive.ArchivedFormTaskSigningStepBEV2> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArchiveTaskV2", Namespace="http://schemas.altinn.no/services/Archive/ReporteeArchive/2010/10")]
    [System.SerializableAttribute()]
    public partial class ArchiveTaskV2 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EndUserSystemIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastChangedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberOfSignaturesAddedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProcessStepID_FKField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SentCompleteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TaskIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserDefinedNumberOfSignaturesRequiredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkflowReferenceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EndUserSystemID {
            get {
                return this.EndUserSystemIDField;
            }
            set {
                if ((this.EndUserSystemIDField.Equals(value) != true)) {
                    this.EndUserSystemIDField = value;
                    this.RaisePropertyChanged("EndUserSystemID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastChanged {
            get {
                return this.LastChangedField;
            }
            set {
                if ((this.LastChangedField.Equals(value) != true)) {
                    this.LastChangedField = value;
                    this.RaisePropertyChanged("LastChanged");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumberOfSignaturesAdded {
            get {
                return this.NumberOfSignaturesAddedField;
            }
            set {
                if ((this.NumberOfSignaturesAddedField.Equals(value) != true)) {
                    this.NumberOfSignaturesAddedField = value;
                    this.RaisePropertyChanged("NumberOfSignaturesAdded");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProcessStepID_FK {
            get {
                return this.ProcessStepID_FKField;
            }
            set {
                if ((this.ProcessStepID_FKField.Equals(value) != true)) {
                    this.ProcessStepID_FKField = value;
                    this.RaisePropertyChanged("ProcessStepID_FK");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SentComplete {
            get {
                return this.SentCompleteField;
            }
            set {
                if ((this.SentCompleteField.Equals(value) != true)) {
                    this.SentCompleteField = value;
                    this.RaisePropertyChanged("SentComplete");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TaskID {
            get {
                return this.TaskIDField;
            }
            set {
                if ((this.TaskIDField.Equals(value) != true)) {
                    this.TaskIDField = value;
                    this.RaisePropertyChanged("TaskID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserDefinedNumberOfSignaturesRequired {
            get {
                return this.UserDefinedNumberOfSignaturesRequiredField;
            }
            set {
                if ((this.UserDefinedNumberOfSignaturesRequiredField.Equals(value) != true)) {
                    this.UserDefinedNumberOfSignaturesRequiredField = value;
                    this.RaisePropertyChanged("UserDefinedNumberOfSignaturesRequired");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkflowReference {
            get {
                return this.WorkflowReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkflowReferenceField, value) != true)) {
                    this.WorkflowReferenceField = value;
                    this.RaisePropertyChanged("WorkflowReference");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArchivedAttachmentBEV2", Namespace="http://schemas.altinn.no/services/Archive/ReporteeArchive/2010/10")]
    [System.SerializableAttribute()]
    public partial class ArchivedAttachmentBEV2 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EC_Endpoint_Client.SOArchive.AttachmentFunctionTypeV2 AttachmentFunctionTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AttachmentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AttachmentNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CreatedByUserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsAddedAfterFormFillinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsEncryptedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EC_Endpoint_Client.SOArchive.AttachmentType MimeTypeNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EC_Endpoint_Client.SOArchive.AttachmentFunctionTypeV2 AttachmentFunctionType {
            get {
                return this.AttachmentFunctionTypeField;
            }
            set {
                if ((this.AttachmentFunctionTypeField.Equals(value) != true)) {
                    this.AttachmentFunctionTypeField = value;
                    this.RaisePropertyChanged("AttachmentFunctionType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AttachmentID {
            get {
                return this.AttachmentIDField;
            }
            set {
                if ((this.AttachmentIDField.Equals(value) != true)) {
                    this.AttachmentIDField = value;
                    this.RaisePropertyChanged("AttachmentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AttachmentName {
            get {
                return this.AttachmentNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AttachmentNameField, value) != true)) {
                    this.AttachmentNameField = value;
                    this.RaisePropertyChanged("AttachmentName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CreatedByUserID {
            get {
                return this.CreatedByUserIDField;
            }
            set {
                if ((this.CreatedByUserIDField.Equals(value) != true)) {
                    this.CreatedByUserIDField = value;
                    this.RaisePropertyChanged("CreatedByUserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDateTime {
            get {
                return this.CreatedDateTimeField;
            }
            set {
                if ((this.CreatedDateTimeField.Equals(value) != true)) {
                    this.CreatedDateTimeField = value;
                    this.RaisePropertyChanged("CreatedDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAddedAfterFormFillin {
            get {
                return this.IsAddedAfterFormFillinField;
            }
            set {
                if ((this.IsAddedAfterFormFillinField.Equals(value) != true)) {
                    this.IsAddedAfterFormFillinField = value;
                    this.RaisePropertyChanged("IsAddedAfterFormFillin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsEncrypted {
            get {
                return this.IsEncryptedField;
            }
            set {
                if ((this.IsEncryptedField.Equals(value) != true)) {
                    this.IsEncryptedField = value;
                    this.RaisePropertyChanged("IsEncrypted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EC_Endpoint_Client.SOArchive.AttachmentType MimeTypeName {
            get {
                return this.MimeTypeNameField;
            }
            set {
                if ((this.MimeTypeNameField.Equals(value) != true)) {
                    this.MimeTypeNameField = value;
                    this.RaisePropertyChanged("MimeTypeName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AttachmentFunctionTypeV2", Namespace="http://schemas.altinn.no/services/ServiceEngine/Subscription/2010/10")]
    public enum AttachmentFunctionTypeV2 : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Default = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unspecified = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Invoice = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AttachmentType", Namespace="http://schemas.altinn.no/services/serviceEntity/2009/10")]
    public enum AttachmentType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        application_None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        application_pdf = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        application_msword = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        application_vnd_ms_excel = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        application_vnd_oasis_opendocument_text = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        application_vnd_oasis_opendocument_presentation = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        application_vnd_oasis_opendocument_spreadsheet = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        application_rtf = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        application_vnd_ms_powerpoint = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        application_postscript = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        application_zip = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        text_plain = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        text_html = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        text_xml = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        text_rtf = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        text_richtext = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        binary_octet_stream = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        not_Applicable = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MTOM = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BASE64 = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        image_jpeg = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        image_gif = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        image_bmp = 22,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArchivedFormBE", Namespace="http://schemas.altinn.no/services/Archive/ReporteeArchive/2009/10")]
    [System.SerializableAttribute()]
    public partial class ArchivedFormBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataFormatIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DataFormatVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FormDataXMLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FormIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FormNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FormPaymentInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FormPresentationFieldValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FormSummaryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ParentReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaymentInformationE2BField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaymentInformationHTMLField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataFormatId {
            get {
                return this.DataFormatIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DataFormatIdField, value) != true)) {
                    this.DataFormatIdField = value;
                    this.RaisePropertyChanged("DataFormatId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DataFormatVersion {
            get {
                return this.DataFormatVersionField;
            }
            set {
                if ((this.DataFormatVersionField.Equals(value) != true)) {
                    this.DataFormatVersionField = value;
                    this.RaisePropertyChanged("DataFormatVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FormDataXML {
            get {
                return this.FormDataXMLField;
            }
            set {
                if ((object.ReferenceEquals(this.FormDataXMLField, value) != true)) {
                    this.FormDataXMLField = value;
                    this.RaisePropertyChanged("FormDataXML");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FormID {
            get {
                return this.FormIDField;
            }
            set {
                if ((this.FormIDField.Equals(value) != true)) {
                    this.FormIDField = value;
                    this.RaisePropertyChanged("FormID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FormName {
            get {
                return this.FormNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FormNameField, value) != true)) {
                    this.FormNameField = value;
                    this.RaisePropertyChanged("FormName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FormPaymentInfo {
            get {
                return this.FormPaymentInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.FormPaymentInfoField, value) != true)) {
                    this.FormPaymentInfoField = value;
                    this.RaisePropertyChanged("FormPaymentInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FormPresentationFieldValue {
            get {
                return this.FormPresentationFieldValueField;
            }
            set {
                if ((object.ReferenceEquals(this.FormPresentationFieldValueField, value) != true)) {
                    this.FormPresentationFieldValueField = value;
                    this.RaisePropertyChanged("FormPresentationFieldValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FormSummary {
            get {
                return this.FormSummaryField;
            }
            set {
                if ((object.ReferenceEquals(this.FormSummaryField, value) != true)) {
                    this.FormSummaryField = value;
                    this.RaisePropertyChanged("FormSummary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ParentReference {
            get {
                return this.ParentReferenceField;
            }
            set {
                if ((this.ParentReferenceField.Equals(value) != true)) {
                    this.ParentReferenceField = value;
                    this.RaisePropertyChanged("ParentReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentInformationE2B {
            get {
                return this.PaymentInformationE2BField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentInformationE2BField, value) != true)) {
                    this.PaymentInformationE2BField = value;
                    this.RaisePropertyChanged("PaymentInformationE2B");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentInformationHTML {
            get {
                return this.PaymentInformationHTMLField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentInformationHTMLField, value) != true)) {
                    this.PaymentInformationHTMLField = value;
                    this.RaisePropertyChanged("PaymentInformationHTML");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArchivedFormTaskSigningStepBEV2", Namespace="http://schemas.altinn.no/services/Archive/ReporteeArchive/2010/10")]
    [System.SerializableAttribute()]
    public partial class ArchivedFormTaskSigningStepBEV2 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AuthenticationLevelIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AuthenticationMethodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CertificateIssuedByNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CertificateIssuedForNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CertificateValidFromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CertificateValidToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EC_Endpoint_Client.SOArchive.WorkFlowGroupSigningType IsSigningAllRequiredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProcessStepIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] SignatureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SignatureIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SignatureTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] SignedAttachmentListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SignedByUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SignedByUserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SignedByUserSSNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] SignedFromListField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AuthenticationLevelID {
            get {
                return this.AuthenticationLevelIDField;
            }
            set {
                if ((this.AuthenticationLevelIDField.Equals(value) != true)) {
                    this.AuthenticationLevelIDField = value;
                    this.RaisePropertyChanged("AuthenticationLevelID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AuthenticationMethod {
            get {
                return this.AuthenticationMethodField;
            }
            set {
                if ((this.AuthenticationMethodField.Equals(value) != true)) {
                    this.AuthenticationMethodField = value;
                    this.RaisePropertyChanged("AuthenticationMethod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CertificateIssuedByName {
            get {
                return this.CertificateIssuedByNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CertificateIssuedByNameField, value) != true)) {
                    this.CertificateIssuedByNameField = value;
                    this.RaisePropertyChanged("CertificateIssuedByName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CertificateIssuedForName {
            get {
                return this.CertificateIssuedForNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CertificateIssuedForNameField, value) != true)) {
                    this.CertificateIssuedForNameField = value;
                    this.RaisePropertyChanged("CertificateIssuedForName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CertificateValidFrom {
            get {
                return this.CertificateValidFromField;
            }
            set {
                if ((this.CertificateValidFromField.Equals(value) != true)) {
                    this.CertificateValidFromField = value;
                    this.RaisePropertyChanged("CertificateValidFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CertificateValidTo {
            get {
                return this.CertificateValidToField;
            }
            set {
                if ((this.CertificateValidToField.Equals(value) != true)) {
                    this.CertificateValidToField = value;
                    this.RaisePropertyChanged("CertificateValidTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDateTime {
            get {
                return this.CreatedDateTimeField;
            }
            set {
                if ((this.CreatedDateTimeField.Equals(value) != true)) {
                    this.CreatedDateTimeField = value;
                    this.RaisePropertyChanged("CreatedDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EC_Endpoint_Client.SOArchive.WorkFlowGroupSigningType IsSigningAllRequired {
            get {
                return this.IsSigningAllRequiredField;
            }
            set {
                if ((this.IsSigningAllRequiredField.Equals(value) != true)) {
                    this.IsSigningAllRequiredField = value;
                    this.RaisePropertyChanged("IsSigningAllRequired");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProcessStepID {
            get {
                return this.ProcessStepIDField;
            }
            set {
                if ((this.ProcessStepIDField.Equals(value) != true)) {
                    this.ProcessStepIDField = value;
                    this.RaisePropertyChanged("ProcessStepID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Signature {
            get {
                return this.SignatureField;
            }
            set {
                if ((object.ReferenceEquals(this.SignatureField, value) != true)) {
                    this.SignatureField = value;
                    this.RaisePropertyChanged("Signature");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SignatureID {
            get {
                return this.SignatureIDField;
            }
            set {
                if ((this.SignatureIDField.Equals(value) != true)) {
                    this.SignatureIDField = value;
                    this.RaisePropertyChanged("SignatureID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SignatureText {
            get {
                return this.SignatureTextField;
            }
            set {
                if ((object.ReferenceEquals(this.SignatureTextField, value) != true)) {
                    this.SignatureTextField = value;
                    this.RaisePropertyChanged("SignatureText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] SignedAttachmentList {
            get {
                return this.SignedAttachmentListField;
            }
            set {
                if ((object.ReferenceEquals(this.SignedAttachmentListField, value) != true)) {
                    this.SignedAttachmentListField = value;
                    this.RaisePropertyChanged("SignedAttachmentList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SignedByUser {
            get {
                return this.SignedByUserField;
            }
            set {
                if ((this.SignedByUserField.Equals(value) != true)) {
                    this.SignedByUserField = value;
                    this.RaisePropertyChanged("SignedByUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SignedByUserName {
            get {
                return this.SignedByUserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SignedByUserNameField, value) != true)) {
                    this.SignedByUserNameField = value;
                    this.RaisePropertyChanged("SignedByUserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SignedByUserSSN {
            get {
                return this.SignedByUserSSNField;
            }
            set {
                if ((object.ReferenceEquals(this.SignedByUserSSNField, value) != true)) {
                    this.SignedByUserSSNField = value;
                    this.RaisePropertyChanged("SignedByUserSSN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] SignedFromList {
            get {
                return this.SignedFromListField;
            }
            set {
                if ((object.ReferenceEquals(this.SignedFromListField, value) != true)) {
                    this.SignedFromListField = value;
                    this.RaisePropertyChanged("SignedFromList");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WorkFlowGroupSigningType", Namespace="http://schemas.altinn.no/services/ServiceEngine/Workflow/2010/10")]
    public enum WorkFlowGroupSigningType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        YES = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NO = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SET_PER_FORM = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.altinn.no/services/Archive/ServiceOwnerArchive/2010/10", ConfigurationName="SOArchive.IServiceOwnerArchiveExternalEC")]
    public interface IServiceOwnerArchiveExternalEC {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://www.altinn.no/services/2009/10) of message TestRequest does not match the default value (http://www.altinn.no/services/Archive/ServiceOwnerArchive/2010/10)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/2009/10/IAltinnContractBase/Test", ReplyAction="http://www.altinn.no/services/2009/10/IAltinnContractBase/TestResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EC_Endpoint_Client.SOArchive.AltinnFault), Action="http://www.altinn.no/services/2009/10/IAltinnContractBase/TestAltinnFaultFault", Name="AltinnFault", Namespace="http://www.altinn.no/services/common/fault/2009/10")]
        EC_Endpoint_Client.SOArchive.TestResponse Test(EC_Endpoint_Client.SOArchive.TestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/2009/10/IAltinnContractBase/Test", ReplyAction="http://www.altinn.no/services/2009/10/IAltinnContractBase/TestResponse")]
        System.Threading.Tasks.Task<EC_Endpoint_Client.SOArchive.TestResponse> TestAsync(EC_Endpoint_Client.SOArchive.TestRequest request);
        
        // CODEGEN: Generating message contract since element name systemUserName from namespace http://www.altinn.no/services/Archive/ServiceOwnerArchive/2010/10 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/Archive/ServiceOwnerArchive/2010/10/IServiceOwnerAr" +
            "chiveExternalEC/GetArchivedFormTaskEC", ReplyAction="http://www.altinn.no/services/Archive/ServiceOwnerArchive/2010/10/IServiceOwnerAr" +
            "chiveExternalEC/GetArchivedFormTaskECResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EC_Endpoint_Client.SOArchive.AltinnFault), Action="http://www.altinn.no/services/Archive/ServiceOwnerArchive/2010/10/IServiceOwnerAr" +
            "chiveExternalEC/GetArchivedFormTaskECAltinnFaultFault", Name="AltinnFault", Namespace="http://www.altinn.no/services/common/fault/2009/10")]
        EC_Endpoint_Client.SOArchive.GetArchivedFormTaskECResponse GetArchivedFormTaskEC(EC_Endpoint_Client.SOArchive.GetArchivedFormTaskECRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/Archive/ServiceOwnerArchive/2010/10/IServiceOwnerAr" +
            "chiveExternalEC/GetArchivedFormTaskEC", ReplyAction="http://www.altinn.no/services/Archive/ServiceOwnerArchive/2010/10/IServiceOwnerAr" +
            "chiveExternalEC/GetArchivedFormTaskECResponse")]
        System.Threading.Tasks.Task<EC_Endpoint_Client.SOArchive.GetArchivedFormTaskECResponse> GetArchivedFormTaskECAsync(EC_Endpoint_Client.SOArchive.GetArchivedFormTaskECRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Test", WrapperNamespace="http://www.altinn.no/services/2009/10", IsWrapped=true)]
    public partial class TestRequest {
        
        public TestRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TestResponse", WrapperNamespace="http://www.altinn.no/services/2009/10", IsWrapped=true)]
    public partial class TestResponse {
        
        public TestResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetArchivedFormTaskECRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetArchivedFormTaskEC", Namespace="http://www.altinn.no/services/Archive/ServiceOwnerArchive/2010/10", Order=0)]
        public EC_Endpoint_Client.SOArchive.GetArchivedFormTaskECRequestBody Body;
        
        public GetArchivedFormTaskECRequest() {
        }
        
        public GetArchivedFormTaskECRequest(EC_Endpoint_Client.SOArchive.GetArchivedFormTaskECRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.altinn.no/services/Archive/ServiceOwnerArchive/2010/10")]
    public partial class GetArchivedFormTaskECRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string systemUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string systemPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int reporteeElementID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<int> languageID;
        
        public GetArchivedFormTaskECRequestBody() {
        }
        
        public GetArchivedFormTaskECRequestBody(string systemUserName, string systemPassword, int reporteeElementID, System.Nullable<int> languageID) {
            this.systemUserName = systemUserName;
            this.systemPassword = systemPassword;
            this.reporteeElementID = reporteeElementID;
            this.languageID = languageID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetArchivedFormTaskECResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetArchivedFormTaskECResponse", Namespace="http://www.altinn.no/services/Archive/ServiceOwnerArchive/2010/10", Order=0)]
        public EC_Endpoint_Client.SOArchive.GetArchivedFormTaskECResponseBody Body;
        
        public GetArchivedFormTaskECResponse() {
        }
        
        public GetArchivedFormTaskECResponse(EC_Endpoint_Client.SOArchive.GetArchivedFormTaskECResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.altinn.no/services/Archive/ServiceOwnerArchive/2010/10")]
    public partial class GetArchivedFormTaskECResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public EC_Endpoint_Client.SOArchive.ArchivedFormTaskV2 GetArchivedFormTaskECResult;
        
        public GetArchivedFormTaskECResponseBody() {
        }
        
        public GetArchivedFormTaskECResponseBody(EC_Endpoint_Client.SOArchive.ArchivedFormTaskV2 GetArchivedFormTaskECResult) {
            this.GetArchivedFormTaskECResult = GetArchivedFormTaskECResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceOwnerArchiveExternalECChannel : EC_Endpoint_Client.SOArchive.IServiceOwnerArchiveExternalEC, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceOwnerArchiveExternalECClient : System.ServiceModel.ClientBase<EC_Endpoint_Client.SOArchive.IServiceOwnerArchiveExternalEC>, EC_Endpoint_Client.SOArchive.IServiceOwnerArchiveExternalEC {
        
        public ServiceOwnerArchiveExternalECClient() {
        }
        
        public ServiceOwnerArchiveExternalECClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceOwnerArchiveExternalECClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOwnerArchiveExternalECClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOwnerArchiveExternalECClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EC_Endpoint_Client.SOArchive.TestResponse EC_Endpoint_Client.SOArchive.IServiceOwnerArchiveExternalEC.Test(EC_Endpoint_Client.SOArchive.TestRequest request) {
            return base.Channel.Test(request);
        }
        
        public void Test() {
            EC_Endpoint_Client.SOArchive.TestRequest inValue = new EC_Endpoint_Client.SOArchive.TestRequest();
            EC_Endpoint_Client.SOArchive.TestResponse retVal = ((EC_Endpoint_Client.SOArchive.IServiceOwnerArchiveExternalEC)(this)).Test(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EC_Endpoint_Client.SOArchive.TestResponse> EC_Endpoint_Client.SOArchive.IServiceOwnerArchiveExternalEC.TestAsync(EC_Endpoint_Client.SOArchive.TestRequest request) {
            return base.Channel.TestAsync(request);
        }
        
        public System.Threading.Tasks.Task<EC_Endpoint_Client.SOArchive.TestResponse> TestAsync() {
            EC_Endpoint_Client.SOArchive.TestRequest inValue = new EC_Endpoint_Client.SOArchive.TestRequest();
            return ((EC_Endpoint_Client.SOArchive.IServiceOwnerArchiveExternalEC)(this)).TestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EC_Endpoint_Client.SOArchive.GetArchivedFormTaskECResponse EC_Endpoint_Client.SOArchive.IServiceOwnerArchiveExternalEC.GetArchivedFormTaskEC(EC_Endpoint_Client.SOArchive.GetArchivedFormTaskECRequest request) {
            return base.Channel.GetArchivedFormTaskEC(request);
        }
        
        public EC_Endpoint_Client.SOArchive.ArchivedFormTaskV2 GetArchivedFormTaskEC(string systemUserName, string systemPassword, int reporteeElementID, System.Nullable<int> languageID) {
            EC_Endpoint_Client.SOArchive.GetArchivedFormTaskECRequest inValue = new EC_Endpoint_Client.SOArchive.GetArchivedFormTaskECRequest();
            inValue.Body = new EC_Endpoint_Client.SOArchive.GetArchivedFormTaskECRequestBody();
            inValue.Body.systemUserName = systemUserName;
            inValue.Body.systemPassword = systemPassword;
            inValue.Body.reporteeElementID = reporteeElementID;
            inValue.Body.languageID = languageID;
            EC_Endpoint_Client.SOArchive.GetArchivedFormTaskECResponse retVal = ((EC_Endpoint_Client.SOArchive.IServiceOwnerArchiveExternalEC)(this)).GetArchivedFormTaskEC(inValue);
            return retVal.Body.GetArchivedFormTaskECResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EC_Endpoint_Client.SOArchive.GetArchivedFormTaskECResponse> EC_Endpoint_Client.SOArchive.IServiceOwnerArchiveExternalEC.GetArchivedFormTaskECAsync(EC_Endpoint_Client.SOArchive.GetArchivedFormTaskECRequest request) {
            return base.Channel.GetArchivedFormTaskECAsync(request);
        }
        
        public System.Threading.Tasks.Task<EC_Endpoint_Client.SOArchive.GetArchivedFormTaskECResponse> GetArchivedFormTaskECAsync(string systemUserName, string systemPassword, int reporteeElementID, System.Nullable<int> languageID) {
            EC_Endpoint_Client.SOArchive.GetArchivedFormTaskECRequest inValue = new EC_Endpoint_Client.SOArchive.GetArchivedFormTaskECRequest();
            inValue.Body = new EC_Endpoint_Client.SOArchive.GetArchivedFormTaskECRequestBody();
            inValue.Body.systemUserName = systemUserName;
            inValue.Body.systemPassword = systemPassword;
            inValue.Body.reporteeElementID = reporteeElementID;
            inValue.Body.languageID = languageID;
            return ((EC_Endpoint_Client.SOArchive.IServiceOwnerArchiveExternalEC)(this)).GetArchivedFormTaskECAsync(inValue);
        }
    }
}
