//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC_Endpoint_Client.ReceiptAgency {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AltinnFault", Namespace="http://www.altinn.no/services/common/fault/2009/10")]
    [System.SerializableAttribute()]
    public partial class AltinnFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AltinnErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AltinnExtendedErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AltinnLocalizedErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AltinnErrorMessage {
            get {
                return this.AltinnErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.AltinnErrorMessageField, value) != true)) {
                    this.AltinnErrorMessageField = value;
                    this.RaisePropertyChanged("AltinnErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AltinnExtendedErrorMessage {
            get {
                return this.AltinnExtendedErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.AltinnExtendedErrorMessageField, value) != true)) {
                    this.AltinnExtendedErrorMessageField = value;
                    this.RaisePropertyChanged("AltinnExtendedErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AltinnLocalizedErrorMessage {
            get {
                return this.AltinnLocalizedErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.AltinnLocalizedErrorMessageField, value) != true)) {
                    this.AltinnLocalizedErrorMessageField = value;
                    this.RaisePropertyChanged("AltinnLocalizedErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorGuid {
            get {
                return this.ErrorGuidField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorGuidField, value) != true)) {
                    this.ErrorGuidField = value;
                    this.RaisePropertyChanged("ErrorGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorID {
            get {
                return this.ErrorIDField;
            }
            set {
                if ((this.ErrorIDField.Equals(value) != true)) {
                    this.ErrorIDField = value;
                    this.RaisePropertyChanged("ErrorID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserGuid {
            get {
                return this.UserGuidField;
            }
            set {
                if ((object.ReferenceEquals(this.UserGuidField, value) != true)) {
                    this.UserGuidField = value;
                    this.RaisePropertyChanged("UserGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIdField, value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReceiptSearchExternal", Namespace="http://schemas.altinn.no/services/Intermediary/Receipt/2009/10")]
    [System.SerializableAttribute()]
    public partial class ReceiptSearchExternal : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReceiptIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EC_Endpoint_Client.ReceiptAgency.ReferenceList ReferencesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReceiptId {
            get {
                return this.ReceiptIdField;
            }
            set {
                if ((this.ReceiptIdField.Equals(value) != true)) {
                    this.ReceiptIdField = value;
                    this.RaisePropertyChanged("ReceiptId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EC_Endpoint_Client.ReceiptAgency.ReferenceList References {
            get {
                return this.ReferencesField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferencesField, value) != true)) {
                    this.ReferencesField = value;
                    this.RaisePropertyChanged("References");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ReferenceList", Namespace="http://schemas.altinn.no/services/Intermediary/Receipt/2009/10", ItemName="Reference")]
    [System.SerializableAttribute()]
    public class ReferenceList : System.Collections.Generic.List<EC_Endpoint_Client.ReceiptAgency.Reference> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Reference", Namespace="http://schemas.altinn.no/services/Intermediary/Receipt/2009/10")]
    [System.SerializableAttribute()]
    public partial class Reference : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EC_Endpoint_Client.ReceiptAgency.ReferenceType ReferenceTypeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferenceValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EC_Endpoint_Client.ReceiptAgency.ReferenceType ReferenceTypeName {
            get {
                return this.ReferenceTypeNameField;
            }
            set {
                if ((this.ReferenceTypeNameField.Equals(value) != true)) {
                    this.ReferenceTypeNameField = value;
                    this.RaisePropertyChanged("ReferenceTypeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReferenceValue {
            get {
                return this.ReferenceValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenceValueField, value) != true)) {
                    this.ReferenceValueField = value;
                    this.RaisePropertyChanged("ReferenceValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReferenceType", Namespace="http://schemas.altinn.no/services/Intermediary/Shipment/2009/10")]
    public enum ReferenceType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotSet = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ExternalShipmentReference = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EndUserSystemReference = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ParentReference = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SendersReference = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WorkFlowReference = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BatchReference = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OutboundShipmentReference = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ReceiversReference = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Altinn1Reference = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OwnerPartyReference = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PartyReference = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ArchiveReference = 12,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReceiptExternal", Namespace="http://schemas.altinn.no/services/Intermediary/Receipt/2009/10")]
    [System.SerializableAttribute()]
    public partial class ReceiptExternal : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastChangedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ParentReceiptIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiptHistoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReceiptIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EC_Endpoint_Client.ReceiptAgency.ReceiptStatusEnum ReceiptStatusCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiptTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EC_Endpoint_Client.ReceiptAgency.ReceiptTypeEnum ReceiptTypeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EC_Endpoint_Client.ReceiptAgency.ReferenceList ReferencesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EC_Endpoint_Client.ReceiptAgency.ReceiptExternalList SubReceiptsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastChanged {
            get {
                return this.LastChangedField;
            }
            set {
                if ((this.LastChangedField.Equals(value) != true)) {
                    this.LastChangedField = value;
                    this.RaisePropertyChanged("LastChanged");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ParentReceiptId {
            get {
                return this.ParentReceiptIdField;
            }
            set {
                if ((this.ParentReceiptIdField.Equals(value) != true)) {
                    this.ParentReceiptIdField = value;
                    this.RaisePropertyChanged("ParentReceiptId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceiptHistory {
            get {
                return this.ReceiptHistoryField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiptHistoryField, value) != true)) {
                    this.ReceiptHistoryField = value;
                    this.RaisePropertyChanged("ReceiptHistory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReceiptId {
            get {
                return this.ReceiptIdField;
            }
            set {
                if ((this.ReceiptIdField.Equals(value) != true)) {
                    this.ReceiptIdField = value;
                    this.RaisePropertyChanged("ReceiptId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EC_Endpoint_Client.ReceiptAgency.ReceiptStatusEnum ReceiptStatusCode {
            get {
                return this.ReceiptStatusCodeField;
            }
            set {
                if ((this.ReceiptStatusCodeField.Equals(value) != true)) {
                    this.ReceiptStatusCodeField = value;
                    this.RaisePropertyChanged("ReceiptStatusCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceiptText {
            get {
                return this.ReceiptTextField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiptTextField, value) != true)) {
                    this.ReceiptTextField = value;
                    this.RaisePropertyChanged("ReceiptText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EC_Endpoint_Client.ReceiptAgency.ReceiptTypeEnum ReceiptTypeName {
            get {
                return this.ReceiptTypeNameField;
            }
            set {
                if ((this.ReceiptTypeNameField.Equals(value) != true)) {
                    this.ReceiptTypeNameField = value;
                    this.RaisePropertyChanged("ReceiptTypeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EC_Endpoint_Client.ReceiptAgency.ReferenceList References {
            get {
                return this.ReferencesField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferencesField, value) != true)) {
                    this.ReferencesField = value;
                    this.RaisePropertyChanged("References");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EC_Endpoint_Client.ReceiptAgency.ReceiptExternalList SubReceipts {
            get {
                return this.SubReceiptsField;
            }
            set {
                if ((object.ReferenceEquals(this.SubReceiptsField, value) != true)) {
                    this.SubReceiptsField = value;
                    this.RaisePropertyChanged("SubReceipts");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReceiptStatusEnum", Namespace="http://schemas.altinn.no/services/Intermediary/Receipt/2009/10")]
    public enum ReceiptStatusEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotSet = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OK = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnExpectedError = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ValidationFailed = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rejected = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReceiptTypeEnum", Namespace="http://schemas.altinn.no/services/Intermediary/Receipt/2009/10")]
    public enum ReceiptTypeEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotSet = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FormTask = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Correspondence = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PINCODE = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Subscription = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Outbound = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PreFill = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegisterDLS = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegisterDSF = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegisterER = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegisterDSFProperty = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegisterDSFStreet = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegisterDSFCountry = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegisterDSFUser = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LookUp = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegisterDSFStreetAdd = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegisterDSFPropertyAdd = 16,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ReceiptExternalList", Namespace="http://schemas.altinn.no/services/Intermediary/Receipt/2009/10", ItemName="ReceiptExternal")]
    [System.SerializableAttribute()]
    public class ReceiptExternalList : System.Collections.Generic.List<EC_Endpoint_Client.ReceiptAgency.ReceiptExternal> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Receipt", Namespace="http://schemas.altinn.no/services/Intermediary/Receipt/2015/06")]
    [System.SerializableAttribute()]
    public partial class Receipt : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastChangedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ParentReceiptIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiptHistoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReceiptIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EC_Endpoint_Client.ReceiptAgency.ReceiptStatusEnum ReceiptStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiptTemplateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiptTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EC_Endpoint_Client.ReceiptAgency.ReceiptType ReceiptTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EC_Endpoint_Client.ReceiptAgency.ReferenceList ReferencesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EC_Endpoint_Client.ReceiptAgency.ReceiptList SubReceiptsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastChanged {
            get {
                return this.LastChangedField;
            }
            set {
                if ((this.LastChangedField.Equals(value) != true)) {
                    this.LastChangedField = value;
                    this.RaisePropertyChanged("LastChanged");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ParentReceiptId {
            get {
                return this.ParentReceiptIdField;
            }
            set {
                if ((this.ParentReceiptIdField.Equals(value) != true)) {
                    this.ParentReceiptIdField = value;
                    this.RaisePropertyChanged("ParentReceiptId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceiptHistory {
            get {
                return this.ReceiptHistoryField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiptHistoryField, value) != true)) {
                    this.ReceiptHistoryField = value;
                    this.RaisePropertyChanged("ReceiptHistory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReceiptId {
            get {
                return this.ReceiptIdField;
            }
            set {
                if ((this.ReceiptIdField.Equals(value) != true)) {
                    this.ReceiptIdField = value;
                    this.RaisePropertyChanged("ReceiptId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EC_Endpoint_Client.ReceiptAgency.ReceiptStatusEnum ReceiptStatus {
            get {
                return this.ReceiptStatusField;
            }
            set {
                if ((this.ReceiptStatusField.Equals(value) != true)) {
                    this.ReceiptStatusField = value;
                    this.RaisePropertyChanged("ReceiptStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceiptTemplate {
            get {
                return this.ReceiptTemplateField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiptTemplateField, value) != true)) {
                    this.ReceiptTemplateField = value;
                    this.RaisePropertyChanged("ReceiptTemplate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceiptText {
            get {
                return this.ReceiptTextField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiptTextField, value) != true)) {
                    this.ReceiptTextField = value;
                    this.RaisePropertyChanged("ReceiptText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EC_Endpoint_Client.ReceiptAgency.ReceiptType ReceiptType {
            get {
                return this.ReceiptTypeField;
            }
            set {
                if ((this.ReceiptTypeField.Equals(value) != true)) {
                    this.ReceiptTypeField = value;
                    this.RaisePropertyChanged("ReceiptType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EC_Endpoint_Client.ReceiptAgency.ReferenceList References {
            get {
                return this.ReferencesField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferencesField, value) != true)) {
                    this.ReferencesField = value;
                    this.RaisePropertyChanged("References");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EC_Endpoint_Client.ReceiptAgency.ReceiptList SubReceipts {
            get {
                return this.SubReceiptsField;
            }
            set {
                if ((object.ReferenceEquals(this.SubReceiptsField, value) != true)) {
                    this.SubReceiptsField = value;
                    this.RaisePropertyChanged("SubReceipts");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReceiptType", Namespace="http://schemas.altinn.no/services/Intermediary/Receipt/2015/06")]
    public enum ReceiptType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotSet = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FormTask = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Correspondence = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PINCODE = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Subscription = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Outbound = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PreFill = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegisterDLS = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegisterDSF = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegisterER = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegisterDSFProperty = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegisterDSFStreet = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegisterDSFCountry = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegisterDSFUser = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LookUp = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegisterDSFStreetAdd = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegisterDSFPropertyAdd = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BrokerService = 17,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ReceiptList", Namespace="http://schemas.altinn.no/services/Intermediary/Receipt/2009/10", ItemName="Receipt")]
    [System.SerializableAttribute()]
    public class ReceiptList : System.Collections.Generic.List<EC_Endpoint_Client.ReceiptAgency.Receipt> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReceiptSaveExternal", Namespace="http://schemas.altinn.no/services/Intermediary/Receipt/2009/10")]
    [System.SerializableAttribute()]
    public partial class ReceiptSaveExternal : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArchiveReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReceiptIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EC_Endpoint_Client.ReceiptAgency.ReceiptStatusEnum ReceiptStatusCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiptTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EC_Endpoint_Client.ReceiptAgency.ReferenceList ReferencesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EC_Endpoint_Client.ReceiptAgency.ReceiptSaveExternalList SubReceiptsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ArchiveReference {
            get {
                return this.ArchiveReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.ArchiveReferenceField, value) != true)) {
                    this.ArchiveReferenceField = value;
                    this.RaisePropertyChanged("ArchiveReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReceiptId {
            get {
                return this.ReceiptIdField;
            }
            set {
                if ((this.ReceiptIdField.Equals(value) != true)) {
                    this.ReceiptIdField = value;
                    this.RaisePropertyChanged("ReceiptId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EC_Endpoint_Client.ReceiptAgency.ReceiptStatusEnum ReceiptStatusCode {
            get {
                return this.ReceiptStatusCodeField;
            }
            set {
                if ((this.ReceiptStatusCodeField.Equals(value) != true)) {
                    this.ReceiptStatusCodeField = value;
                    this.RaisePropertyChanged("ReceiptStatusCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceiptText {
            get {
                return this.ReceiptTextField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiptTextField, value) != true)) {
                    this.ReceiptTextField = value;
                    this.RaisePropertyChanged("ReceiptText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EC_Endpoint_Client.ReceiptAgency.ReferenceList References {
            get {
                return this.ReferencesField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferencesField, value) != true)) {
                    this.ReferencesField = value;
                    this.RaisePropertyChanged("References");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EC_Endpoint_Client.ReceiptAgency.ReceiptSaveExternalList SubReceipts {
            get {
                return this.SubReceiptsField;
            }
            set {
                if ((object.ReferenceEquals(this.SubReceiptsField, value) != true)) {
                    this.SubReceiptsField = value;
                    this.RaisePropertyChanged("SubReceipts");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ReceiptSaveExternalList", Namespace="http://schemas.altinn.no/services/Intermediary/Receipt/2009/10", ItemName="ReceiptSaveExternal")]
    [System.SerializableAttribute()]
    public class ReceiptSaveExternalList : System.Collections.Generic.List<EC_Endpoint_Client.ReceiptAgency.ReceiptSaveExternal> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.altinn.no/services/Intermediary/Receipt/2010/10", ConfigurationName="ReceiptAgency.IReceiptAgencyExternalEC")]
    public interface IReceiptAgencyExternalEC {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://www.altinn.no/services/2009/10) of message TestRequest does not match the default value (http://www.altinn.no/services/Intermediary/Receipt/2010/10)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/2009/10/IAltinnContractBase/Test", ReplyAction="http://www.altinn.no/services/2009/10/IAltinnContractBase/TestResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EC_Endpoint_Client.ReceiptAgency.AltinnFault), Action="http://www.altinn.no/services/2009/10/IAltinnContractBase/TestAltinnFaultFault", Name="AltinnFault", Namespace="http://www.altinn.no/services/common/fault/2009/10")]
        EC_Endpoint_Client.ReceiptAgency.TestResponse Test(EC_Endpoint_Client.ReceiptAgency.TestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/2009/10/IAltinnContractBase/Test", ReplyAction="http://www.altinn.no/services/2009/10/IAltinnContractBase/TestResponse")]
        System.Threading.Tasks.Task<EC_Endpoint_Client.ReceiptAgency.TestResponse> TestAsync(EC_Endpoint_Client.ReceiptAgency.TestRequest request);
        
        // CODEGEN: Generating message contract since element name systemUserName from namespace http://www.altinn.no/services/Intermediary/Receipt/2010/10 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/Intermediary/Receipt/2010/10/IReceiptAgencyExternal" +
            "EC/GetReceiptEC", ReplyAction="http://www.altinn.no/services/Intermediary/Receipt/2010/10/IReceiptAgencyExternal" +
            "EC/GetReceiptECResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EC_Endpoint_Client.ReceiptAgency.AltinnFault), Action="http://www.altinn.no/services/Intermediary/Receipt/2010/10/IReceiptAgencyExternal" +
            "EC/GetReceiptECAltinnFaultFault", Name="AltinnFault", Namespace="http://www.altinn.no/services/common/fault/2009/10")]
        EC_Endpoint_Client.ReceiptAgency.GetReceiptECResponse GetReceiptEC(EC_Endpoint_Client.ReceiptAgency.GetReceiptECRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/Intermediary/Receipt/2010/10/IReceiptAgencyExternal" +
            "EC/GetReceiptEC", ReplyAction="http://www.altinn.no/services/Intermediary/Receipt/2010/10/IReceiptAgencyExternal" +
            "EC/GetReceiptECResponse")]
        System.Threading.Tasks.Task<EC_Endpoint_Client.ReceiptAgency.GetReceiptECResponse> GetReceiptECAsync(EC_Endpoint_Client.ReceiptAgency.GetReceiptECRequest request);
        
        // CODEGEN: Generating message contract since element name systemUserName from namespace http://www.altinn.no/services/Intermediary/Receipt/2010/10 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/Intermediary/Receipt/2010/10/IReceiptAgencyExternal" +
            "EC/GetReceiptECV2", ReplyAction="http://www.altinn.no/services/Intermediary/Receipt/2010/10/IReceiptAgencyExternal" +
            "EC/GetReceiptECV2Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(EC_Endpoint_Client.ReceiptAgency.AltinnFault), Action="http://www.altinn.no/services/Intermediary/Receipt/2010/10/IReceiptAgencyExternal" +
            "EC/GetReceiptECV2AltinnFaultFault", Name="AltinnFault", Namespace="http://www.altinn.no/services/common/fault/2009/10")]
        EC_Endpoint_Client.ReceiptAgency.GetReceiptECV2Response GetReceiptECV2(EC_Endpoint_Client.ReceiptAgency.GetReceiptECV2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/Intermediary/Receipt/2010/10/IReceiptAgencyExternal" +
            "EC/GetReceiptECV2", ReplyAction="http://www.altinn.no/services/Intermediary/Receipt/2010/10/IReceiptAgencyExternal" +
            "EC/GetReceiptECV2Response")]
        System.Threading.Tasks.Task<EC_Endpoint_Client.ReceiptAgency.GetReceiptECV2Response> GetReceiptECV2Async(EC_Endpoint_Client.ReceiptAgency.GetReceiptECV2Request request);
        
        // CODEGEN: Generating message contract since element name systemUserName from namespace http://www.altinn.no/services/Intermediary/Receipt/2010/10 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/Intermediary/Receipt/2010/10/IReceiptAgencyExternal" +
            "EC/GetReceiptListEC", ReplyAction="http://www.altinn.no/services/Intermediary/Receipt/2010/10/IReceiptAgencyExternal" +
            "EC/GetReceiptListECResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EC_Endpoint_Client.ReceiptAgency.AltinnFault), Action="http://www.altinn.no/services/Intermediary/Receipt/2010/10/IReceiptAgencyExternal" +
            "EC/GetReceiptListECAltinnFaultFault", Name="AltinnFault", Namespace="http://www.altinn.no/services/common/fault/2009/10")]
        EC_Endpoint_Client.ReceiptAgency.GetReceiptListECResponse GetReceiptListEC(EC_Endpoint_Client.ReceiptAgency.GetReceiptListECRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/Intermediary/Receipt/2010/10/IReceiptAgencyExternal" +
            "EC/GetReceiptListEC", ReplyAction="http://www.altinn.no/services/Intermediary/Receipt/2010/10/IReceiptAgencyExternal" +
            "EC/GetReceiptListECResponse")]
        System.Threading.Tasks.Task<EC_Endpoint_Client.ReceiptAgency.GetReceiptListECResponse> GetReceiptListECAsync(EC_Endpoint_Client.ReceiptAgency.GetReceiptListECRequest request);
        
        // CODEGEN: Generating message contract since element name systemUserName from namespace http://www.altinn.no/services/Intermediary/Receipt/2010/10 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/Intermediary/Receipt/2010/10/IReceiptAgencyExternal" +
            "EC/GetReceiptListECV2", ReplyAction="http://www.altinn.no/services/Intermediary/Receipt/2010/10/IReceiptAgencyExternal" +
            "EC/GetReceiptListECV2Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(EC_Endpoint_Client.ReceiptAgency.AltinnFault), Action="http://www.altinn.no/services/Intermediary/Receipt/2010/10/IReceiptAgencyExternal" +
            "EC/GetReceiptListECV2AltinnFaultFault", Name="AltinnFault", Namespace="http://www.altinn.no/services/common/fault/2009/10")]
        EC_Endpoint_Client.ReceiptAgency.GetReceiptListECV2Response GetReceiptListECV2(EC_Endpoint_Client.ReceiptAgency.GetReceiptListECV2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/Intermediary/Receipt/2010/10/IReceiptAgencyExternal" +
            "EC/GetReceiptListECV2", ReplyAction="http://www.altinn.no/services/Intermediary/Receipt/2010/10/IReceiptAgencyExternal" +
            "EC/GetReceiptListECV2Response")]
        System.Threading.Tasks.Task<EC_Endpoint_Client.ReceiptAgency.GetReceiptListECV2Response> GetReceiptListECV2Async(EC_Endpoint_Client.ReceiptAgency.GetReceiptListECV2Request request);
        
        // CODEGEN: Generating message contract since element name systemUserName from namespace http://www.altinn.no/services/Intermediary/Receipt/2010/10 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/Intermediary/Receipt/2010/10/IReceiptAgencyExternal" +
            "EC/SaveReceiptEC", ReplyAction="http://www.altinn.no/services/Intermediary/Receipt/2010/10/IReceiptAgencyExternal" +
            "EC/SaveReceiptECResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EC_Endpoint_Client.ReceiptAgency.AltinnFault), Action="http://www.altinn.no/services/Intermediary/Receipt/2010/10/IReceiptAgencyExternal" +
            "EC/SaveReceiptECAltinnFaultFault", Name="AltinnFault", Namespace="http://www.altinn.no/services/common/fault/2009/10")]
        EC_Endpoint_Client.ReceiptAgency.SaveReceiptECResponse SaveReceiptEC(EC_Endpoint_Client.ReceiptAgency.SaveReceiptECRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/Intermediary/Receipt/2010/10/IReceiptAgencyExternal" +
            "EC/SaveReceiptEC", ReplyAction="http://www.altinn.no/services/Intermediary/Receipt/2010/10/IReceiptAgencyExternal" +
            "EC/SaveReceiptECResponse")]
        System.Threading.Tasks.Task<EC_Endpoint_Client.ReceiptAgency.SaveReceiptECResponse> SaveReceiptECAsync(EC_Endpoint_Client.ReceiptAgency.SaveReceiptECRequest request);
        
        // CODEGEN: Generating message contract since element name systemUserName from namespace http://www.altinn.no/services/Intermediary/Receipt/2010/10 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/Intermediary/Receipt/2010/10/IReceiptAgencyExternal" +
            "EC/UpdateReceiptEC", ReplyAction="http://www.altinn.no/services/Intermediary/Receipt/2010/10/IReceiptAgencyExternal" +
            "EC/UpdateReceiptECResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EC_Endpoint_Client.ReceiptAgency.AltinnFault), Action="http://www.altinn.no/services/Intermediary/Receipt/2010/10/IReceiptAgencyExternal" +
            "EC/UpdateReceiptECAltinnFaultFault", Name="AltinnFault", Namespace="http://www.altinn.no/services/common/fault/2009/10")]
        EC_Endpoint_Client.ReceiptAgency.UpdateReceiptECResponse UpdateReceiptEC(EC_Endpoint_Client.ReceiptAgency.UpdateReceiptECRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/Intermediary/Receipt/2010/10/IReceiptAgencyExternal" +
            "EC/UpdateReceiptEC", ReplyAction="http://www.altinn.no/services/Intermediary/Receipt/2010/10/IReceiptAgencyExternal" +
            "EC/UpdateReceiptECResponse")]
        System.Threading.Tasks.Task<EC_Endpoint_Client.ReceiptAgency.UpdateReceiptECResponse> UpdateReceiptECAsync(EC_Endpoint_Client.ReceiptAgency.UpdateReceiptECRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Test", WrapperNamespace="http://www.altinn.no/services/2009/10", IsWrapped=true)]
    public partial class TestRequest {
        
        public TestRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TestResponse", WrapperNamespace="http://www.altinn.no/services/2009/10", IsWrapped=true)]
    public partial class TestResponse {
        
        public TestResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetReceiptECRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetReceiptEC", Namespace="http://www.altinn.no/services/Intermediary/Receipt/2010/10", Order=0)]
        public EC_Endpoint_Client.ReceiptAgency.GetReceiptECRequestBody Body;
        
        public GetReceiptECRequest() {
        }
        
        public GetReceiptECRequest(EC_Endpoint_Client.ReceiptAgency.GetReceiptECRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.altinn.no/services/Intermediary/Receipt/2010/10")]
    public partial class GetReceiptECRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string systemUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string systemPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public EC_Endpoint_Client.ReceiptAgency.ReceiptSearchExternal receipt;
        
        public GetReceiptECRequestBody() {
        }
        
        public GetReceiptECRequestBody(string systemUserName, string systemPassword, EC_Endpoint_Client.ReceiptAgency.ReceiptSearchExternal receipt) {
            this.systemUserName = systemUserName;
            this.systemPassword = systemPassword;
            this.receipt = receipt;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetReceiptECResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetReceiptECResponse", Namespace="http://www.altinn.no/services/Intermediary/Receipt/2010/10", Order=0)]
        public EC_Endpoint_Client.ReceiptAgency.GetReceiptECResponseBody Body;
        
        public GetReceiptECResponse() {
        }
        
        public GetReceiptECResponse(EC_Endpoint_Client.ReceiptAgency.GetReceiptECResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.altinn.no/services/Intermediary/Receipt/2010/10")]
    public partial class GetReceiptECResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public EC_Endpoint_Client.ReceiptAgency.ReceiptExternal GetReceiptECResult;
        
        public GetReceiptECResponseBody() {
        }
        
        public GetReceiptECResponseBody(EC_Endpoint_Client.ReceiptAgency.ReceiptExternal GetReceiptECResult) {
            this.GetReceiptECResult = GetReceiptECResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetReceiptECV2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetReceiptECV2", Namespace="http://www.altinn.no/services/Intermediary/Receipt/2010/10", Order=0)]
        public EC_Endpoint_Client.ReceiptAgency.GetReceiptECV2RequestBody Body;
        
        public GetReceiptECV2Request() {
        }
        
        public GetReceiptECV2Request(EC_Endpoint_Client.ReceiptAgency.GetReceiptECV2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.altinn.no/services/Intermediary/Receipt/2010/10")]
    public partial class GetReceiptECV2RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string systemUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string systemPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public EC_Endpoint_Client.ReceiptAgency.ReceiptSearchExternal receipt;
        
        public GetReceiptECV2RequestBody() {
        }
        
        public GetReceiptECV2RequestBody(string systemUserName, string systemPassword, EC_Endpoint_Client.ReceiptAgency.ReceiptSearchExternal receipt) {
            this.systemUserName = systemUserName;
            this.systemPassword = systemPassword;
            this.receipt = receipt;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetReceiptECV2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetReceiptECV2Response", Namespace="http://www.altinn.no/services/Intermediary/Receipt/2010/10", Order=0)]
        public EC_Endpoint_Client.ReceiptAgency.GetReceiptECV2ResponseBody Body;
        
        public GetReceiptECV2Response() {
        }
        
        public GetReceiptECV2Response(EC_Endpoint_Client.ReceiptAgency.GetReceiptECV2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.altinn.no/services/Intermediary/Receipt/2010/10")]
    public partial class GetReceiptECV2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public EC_Endpoint_Client.ReceiptAgency.Receipt GetReceiptECV2Result;
        
        public GetReceiptECV2ResponseBody() {
        }
        
        public GetReceiptECV2ResponseBody(EC_Endpoint_Client.ReceiptAgency.Receipt GetReceiptECV2Result) {
            this.GetReceiptECV2Result = GetReceiptECV2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetReceiptListECRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetReceiptListEC", Namespace="http://www.altinn.no/services/Intermediary/Receipt/2010/10", Order=0)]
        public EC_Endpoint_Client.ReceiptAgency.GetReceiptListECRequestBody Body;
        
        public GetReceiptListECRequest() {
        }
        
        public GetReceiptListECRequest(EC_Endpoint_Client.ReceiptAgency.GetReceiptListECRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.altinn.no/services/Intermediary/Receipt/2010/10")]
    public partial class GetReceiptListECRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string systemUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string systemPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public EC_Endpoint_Client.ReceiptAgency.ReceiptTypeEnum receiptTypeName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime dateFrom;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime dateTo;
        
        public GetReceiptListECRequestBody() {
        }
        
        public GetReceiptListECRequestBody(string systemUserName, string systemPassword, EC_Endpoint_Client.ReceiptAgency.ReceiptTypeEnum receiptTypeName, System.DateTime dateFrom, System.DateTime dateTo) {
            this.systemUserName = systemUserName;
            this.systemPassword = systemPassword;
            this.receiptTypeName = receiptTypeName;
            this.dateFrom = dateFrom;
            this.dateTo = dateTo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetReceiptListECResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetReceiptListECResponse", Namespace="http://www.altinn.no/services/Intermediary/Receipt/2010/10", Order=0)]
        public EC_Endpoint_Client.ReceiptAgency.GetReceiptListECResponseBody Body;
        
        public GetReceiptListECResponse() {
        }
        
        public GetReceiptListECResponse(EC_Endpoint_Client.ReceiptAgency.GetReceiptListECResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.altinn.no/services/Intermediary/Receipt/2010/10")]
    public partial class GetReceiptListECResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public EC_Endpoint_Client.ReceiptAgency.ReceiptExternalList GetReceiptListECResult;
        
        public GetReceiptListECResponseBody() {
        }
        
        public GetReceiptListECResponseBody(EC_Endpoint_Client.ReceiptAgency.ReceiptExternalList GetReceiptListECResult) {
            this.GetReceiptListECResult = GetReceiptListECResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetReceiptListECV2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetReceiptListECV2", Namespace="http://www.altinn.no/services/Intermediary/Receipt/2010/10", Order=0)]
        public EC_Endpoint_Client.ReceiptAgency.GetReceiptListECV2RequestBody Body;
        
        public GetReceiptListECV2Request() {
        }
        
        public GetReceiptListECV2Request(EC_Endpoint_Client.ReceiptAgency.GetReceiptListECV2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.altinn.no/services/Intermediary/Receipt/2010/10")]
    public partial class GetReceiptListECV2RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string systemUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string systemPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public EC_Endpoint_Client.ReceiptAgency.ReceiptType receiptTypeName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime dateFrom;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime dateTo;
        
        public GetReceiptListECV2RequestBody() {
        }
        
        public GetReceiptListECV2RequestBody(string systemUserName, string systemPassword, EC_Endpoint_Client.ReceiptAgency.ReceiptType receiptTypeName, System.DateTime dateFrom, System.DateTime dateTo) {
            this.systemUserName = systemUserName;
            this.systemPassword = systemPassword;
            this.receiptTypeName = receiptTypeName;
            this.dateFrom = dateFrom;
            this.dateTo = dateTo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetReceiptListECV2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetReceiptListECV2Response", Namespace="http://www.altinn.no/services/Intermediary/Receipt/2010/10", Order=0)]
        public EC_Endpoint_Client.ReceiptAgency.GetReceiptListECV2ResponseBody Body;
        
        public GetReceiptListECV2Response() {
        }
        
        public GetReceiptListECV2Response(EC_Endpoint_Client.ReceiptAgency.GetReceiptListECV2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.altinn.no/services/Intermediary/Receipt/2010/10")]
    public partial class GetReceiptListECV2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public EC_Endpoint_Client.ReceiptAgency.ReceiptList GetReceiptListECV2Result;
        
        public GetReceiptListECV2ResponseBody() {
        }
        
        public GetReceiptListECV2ResponseBody(EC_Endpoint_Client.ReceiptAgency.ReceiptList GetReceiptListECV2Result) {
            this.GetReceiptListECV2Result = GetReceiptListECV2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveReceiptECRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveReceiptEC", Namespace="http://www.altinn.no/services/Intermediary/Receipt/2010/10", Order=0)]
        public EC_Endpoint_Client.ReceiptAgency.SaveReceiptECRequestBody Body;
        
        public SaveReceiptECRequest() {
        }
        
        public SaveReceiptECRequest(EC_Endpoint_Client.ReceiptAgency.SaveReceiptECRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.altinn.no/services/Intermediary/Receipt/2010/10")]
    public partial class SaveReceiptECRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string systemUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string systemPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public EC_Endpoint_Client.ReceiptAgency.ReceiptSaveExternal receipt;
        
        public SaveReceiptECRequestBody() {
        }
        
        public SaveReceiptECRequestBody(string systemUserName, string systemPassword, EC_Endpoint_Client.ReceiptAgency.ReceiptSaveExternal receipt) {
            this.systemUserName = systemUserName;
            this.systemPassword = systemPassword;
            this.receipt = receipt;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveReceiptECResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveReceiptECResponse", Namespace="http://www.altinn.no/services/Intermediary/Receipt/2010/10", Order=0)]
        public EC_Endpoint_Client.ReceiptAgency.SaveReceiptECResponseBody Body;
        
        public SaveReceiptECResponse() {
        }
        
        public SaveReceiptECResponse(EC_Endpoint_Client.ReceiptAgency.SaveReceiptECResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.altinn.no/services/Intermediary/Receipt/2010/10")]
    public partial class SaveReceiptECResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public EC_Endpoint_Client.ReceiptAgency.ReceiptExternal SaveReceiptECResult;
        
        public SaveReceiptECResponseBody() {
        }
        
        public SaveReceiptECResponseBody(EC_Endpoint_Client.ReceiptAgency.ReceiptExternal SaveReceiptECResult) {
            this.SaveReceiptECResult = SaveReceiptECResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateReceiptECRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateReceiptEC", Namespace="http://www.altinn.no/services/Intermediary/Receipt/2010/10", Order=0)]
        public EC_Endpoint_Client.ReceiptAgency.UpdateReceiptECRequestBody Body;
        
        public UpdateReceiptECRequest() {
        }
        
        public UpdateReceiptECRequest(EC_Endpoint_Client.ReceiptAgency.UpdateReceiptECRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.altinn.no/services/Intermediary/Receipt/2010/10")]
    public partial class UpdateReceiptECRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string systemUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string systemPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public EC_Endpoint_Client.ReceiptAgency.ReceiptSaveExternal receipt;
        
        public UpdateReceiptECRequestBody() {
        }
        
        public UpdateReceiptECRequestBody(string systemUserName, string systemPassword, EC_Endpoint_Client.ReceiptAgency.ReceiptSaveExternal receipt) {
            this.systemUserName = systemUserName;
            this.systemPassword = systemPassword;
            this.receipt = receipt;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateReceiptECResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateReceiptECResponse", Namespace="http://www.altinn.no/services/Intermediary/Receipt/2010/10", Order=0)]
        public EC_Endpoint_Client.ReceiptAgency.UpdateReceiptECResponseBody Body;
        
        public UpdateReceiptECResponse() {
        }
        
        public UpdateReceiptECResponse(EC_Endpoint_Client.ReceiptAgency.UpdateReceiptECResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.altinn.no/services/Intermediary/Receipt/2010/10")]
    public partial class UpdateReceiptECResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public EC_Endpoint_Client.ReceiptAgency.Receipt UpdateReceiptECResult;
        
        public UpdateReceiptECResponseBody() {
        }
        
        public UpdateReceiptECResponseBody(EC_Endpoint_Client.ReceiptAgency.Receipt UpdateReceiptECResult) {
            this.UpdateReceiptECResult = UpdateReceiptECResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReceiptAgencyExternalECChannel : EC_Endpoint_Client.ReceiptAgency.IReceiptAgencyExternalEC, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReceiptAgencyExternalECClient : System.ServiceModel.ClientBase<EC_Endpoint_Client.ReceiptAgency.IReceiptAgencyExternalEC>, EC_Endpoint_Client.ReceiptAgency.IReceiptAgencyExternalEC {
        
        public ReceiptAgencyExternalECClient() {
        }
        
        public ReceiptAgencyExternalECClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReceiptAgencyExternalECClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReceiptAgencyExternalECClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReceiptAgencyExternalECClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EC_Endpoint_Client.ReceiptAgency.TestResponse EC_Endpoint_Client.ReceiptAgency.IReceiptAgencyExternalEC.Test(EC_Endpoint_Client.ReceiptAgency.TestRequest request) {
            return base.Channel.Test(request);
        }
        
        public void Test() {
            EC_Endpoint_Client.ReceiptAgency.TestRequest inValue = new EC_Endpoint_Client.ReceiptAgency.TestRequest();
            EC_Endpoint_Client.ReceiptAgency.TestResponse retVal = ((EC_Endpoint_Client.ReceiptAgency.IReceiptAgencyExternalEC)(this)).Test(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EC_Endpoint_Client.ReceiptAgency.TestResponse> EC_Endpoint_Client.ReceiptAgency.IReceiptAgencyExternalEC.TestAsync(EC_Endpoint_Client.ReceiptAgency.TestRequest request) {
            return base.Channel.TestAsync(request);
        }
        
        public System.Threading.Tasks.Task<EC_Endpoint_Client.ReceiptAgency.TestResponse> TestAsync() {
            EC_Endpoint_Client.ReceiptAgency.TestRequest inValue = new EC_Endpoint_Client.ReceiptAgency.TestRequest();
            return ((EC_Endpoint_Client.ReceiptAgency.IReceiptAgencyExternalEC)(this)).TestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EC_Endpoint_Client.ReceiptAgency.GetReceiptECResponse EC_Endpoint_Client.ReceiptAgency.IReceiptAgencyExternalEC.GetReceiptEC(EC_Endpoint_Client.ReceiptAgency.GetReceiptECRequest request) {
            return base.Channel.GetReceiptEC(request);
        }
        
        public EC_Endpoint_Client.ReceiptAgency.ReceiptExternal GetReceiptEC(string systemUserName, string systemPassword, EC_Endpoint_Client.ReceiptAgency.ReceiptSearchExternal receipt) {
            EC_Endpoint_Client.ReceiptAgency.GetReceiptECRequest inValue = new EC_Endpoint_Client.ReceiptAgency.GetReceiptECRequest();
            inValue.Body = new EC_Endpoint_Client.ReceiptAgency.GetReceiptECRequestBody();
            inValue.Body.systemUserName = systemUserName;
            inValue.Body.systemPassword = systemPassword;
            inValue.Body.receipt = receipt;
            EC_Endpoint_Client.ReceiptAgency.GetReceiptECResponse retVal = ((EC_Endpoint_Client.ReceiptAgency.IReceiptAgencyExternalEC)(this)).GetReceiptEC(inValue);
            return retVal.Body.GetReceiptECResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EC_Endpoint_Client.ReceiptAgency.GetReceiptECResponse> EC_Endpoint_Client.ReceiptAgency.IReceiptAgencyExternalEC.GetReceiptECAsync(EC_Endpoint_Client.ReceiptAgency.GetReceiptECRequest request) {
            return base.Channel.GetReceiptECAsync(request);
        }
        
        public System.Threading.Tasks.Task<EC_Endpoint_Client.ReceiptAgency.GetReceiptECResponse> GetReceiptECAsync(string systemUserName, string systemPassword, EC_Endpoint_Client.ReceiptAgency.ReceiptSearchExternal receipt) {
            EC_Endpoint_Client.ReceiptAgency.GetReceiptECRequest inValue = new EC_Endpoint_Client.ReceiptAgency.GetReceiptECRequest();
            inValue.Body = new EC_Endpoint_Client.ReceiptAgency.GetReceiptECRequestBody();
            inValue.Body.systemUserName = systemUserName;
            inValue.Body.systemPassword = systemPassword;
            inValue.Body.receipt = receipt;
            return ((EC_Endpoint_Client.ReceiptAgency.IReceiptAgencyExternalEC)(this)).GetReceiptECAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EC_Endpoint_Client.ReceiptAgency.GetReceiptECV2Response EC_Endpoint_Client.ReceiptAgency.IReceiptAgencyExternalEC.GetReceiptECV2(EC_Endpoint_Client.ReceiptAgency.GetReceiptECV2Request request) {
            return base.Channel.GetReceiptECV2(request);
        }
        
        public EC_Endpoint_Client.ReceiptAgency.Receipt GetReceiptECV2(string systemUserName, string systemPassword, EC_Endpoint_Client.ReceiptAgency.ReceiptSearchExternal receipt) {
            EC_Endpoint_Client.ReceiptAgency.GetReceiptECV2Request inValue = new EC_Endpoint_Client.ReceiptAgency.GetReceiptECV2Request();
            inValue.Body = new EC_Endpoint_Client.ReceiptAgency.GetReceiptECV2RequestBody();
            inValue.Body.systemUserName = systemUserName;
            inValue.Body.systemPassword = systemPassword;
            inValue.Body.receipt = receipt;
            EC_Endpoint_Client.ReceiptAgency.GetReceiptECV2Response retVal = ((EC_Endpoint_Client.ReceiptAgency.IReceiptAgencyExternalEC)(this)).GetReceiptECV2(inValue);
            return retVal.Body.GetReceiptECV2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EC_Endpoint_Client.ReceiptAgency.GetReceiptECV2Response> EC_Endpoint_Client.ReceiptAgency.IReceiptAgencyExternalEC.GetReceiptECV2Async(EC_Endpoint_Client.ReceiptAgency.GetReceiptECV2Request request) {
            return base.Channel.GetReceiptECV2Async(request);
        }
        
        public System.Threading.Tasks.Task<EC_Endpoint_Client.ReceiptAgency.GetReceiptECV2Response> GetReceiptECV2Async(string systemUserName, string systemPassword, EC_Endpoint_Client.ReceiptAgency.ReceiptSearchExternal receipt) {
            EC_Endpoint_Client.ReceiptAgency.GetReceiptECV2Request inValue = new EC_Endpoint_Client.ReceiptAgency.GetReceiptECV2Request();
            inValue.Body = new EC_Endpoint_Client.ReceiptAgency.GetReceiptECV2RequestBody();
            inValue.Body.systemUserName = systemUserName;
            inValue.Body.systemPassword = systemPassword;
            inValue.Body.receipt = receipt;
            return ((EC_Endpoint_Client.ReceiptAgency.IReceiptAgencyExternalEC)(this)).GetReceiptECV2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EC_Endpoint_Client.ReceiptAgency.GetReceiptListECResponse EC_Endpoint_Client.ReceiptAgency.IReceiptAgencyExternalEC.GetReceiptListEC(EC_Endpoint_Client.ReceiptAgency.GetReceiptListECRequest request) {
            return base.Channel.GetReceiptListEC(request);
        }
        
        public EC_Endpoint_Client.ReceiptAgency.ReceiptExternalList GetReceiptListEC(string systemUserName, string systemPassword, EC_Endpoint_Client.ReceiptAgency.ReceiptTypeEnum receiptTypeName, System.DateTime dateFrom, System.DateTime dateTo) {
            EC_Endpoint_Client.ReceiptAgency.GetReceiptListECRequest inValue = new EC_Endpoint_Client.ReceiptAgency.GetReceiptListECRequest();
            inValue.Body = new EC_Endpoint_Client.ReceiptAgency.GetReceiptListECRequestBody();
            inValue.Body.systemUserName = systemUserName;
            inValue.Body.systemPassword = systemPassword;
            inValue.Body.receiptTypeName = receiptTypeName;
            inValue.Body.dateFrom = dateFrom;
            inValue.Body.dateTo = dateTo;
            EC_Endpoint_Client.ReceiptAgency.GetReceiptListECResponse retVal = ((EC_Endpoint_Client.ReceiptAgency.IReceiptAgencyExternalEC)(this)).GetReceiptListEC(inValue);
            return retVal.Body.GetReceiptListECResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EC_Endpoint_Client.ReceiptAgency.GetReceiptListECResponse> EC_Endpoint_Client.ReceiptAgency.IReceiptAgencyExternalEC.GetReceiptListECAsync(EC_Endpoint_Client.ReceiptAgency.GetReceiptListECRequest request) {
            return base.Channel.GetReceiptListECAsync(request);
        }
        
        public System.Threading.Tasks.Task<EC_Endpoint_Client.ReceiptAgency.GetReceiptListECResponse> GetReceiptListECAsync(string systemUserName, string systemPassword, EC_Endpoint_Client.ReceiptAgency.ReceiptTypeEnum receiptTypeName, System.DateTime dateFrom, System.DateTime dateTo) {
            EC_Endpoint_Client.ReceiptAgency.GetReceiptListECRequest inValue = new EC_Endpoint_Client.ReceiptAgency.GetReceiptListECRequest();
            inValue.Body = new EC_Endpoint_Client.ReceiptAgency.GetReceiptListECRequestBody();
            inValue.Body.systemUserName = systemUserName;
            inValue.Body.systemPassword = systemPassword;
            inValue.Body.receiptTypeName = receiptTypeName;
            inValue.Body.dateFrom = dateFrom;
            inValue.Body.dateTo = dateTo;
            return ((EC_Endpoint_Client.ReceiptAgency.IReceiptAgencyExternalEC)(this)).GetReceiptListECAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EC_Endpoint_Client.ReceiptAgency.GetReceiptListECV2Response EC_Endpoint_Client.ReceiptAgency.IReceiptAgencyExternalEC.GetReceiptListECV2(EC_Endpoint_Client.ReceiptAgency.GetReceiptListECV2Request request) {
            return base.Channel.GetReceiptListECV2(request);
        }
        
        public EC_Endpoint_Client.ReceiptAgency.ReceiptList GetReceiptListECV2(string systemUserName, string systemPassword, EC_Endpoint_Client.ReceiptAgency.ReceiptType receiptTypeName, System.DateTime dateFrom, System.DateTime dateTo) {
            EC_Endpoint_Client.ReceiptAgency.GetReceiptListECV2Request inValue = new EC_Endpoint_Client.ReceiptAgency.GetReceiptListECV2Request();
            inValue.Body = new EC_Endpoint_Client.ReceiptAgency.GetReceiptListECV2RequestBody();
            inValue.Body.systemUserName = systemUserName;
            inValue.Body.systemPassword = systemPassword;
            inValue.Body.receiptTypeName = receiptTypeName;
            inValue.Body.dateFrom = dateFrom;
            inValue.Body.dateTo = dateTo;
            EC_Endpoint_Client.ReceiptAgency.GetReceiptListECV2Response retVal = ((EC_Endpoint_Client.ReceiptAgency.IReceiptAgencyExternalEC)(this)).GetReceiptListECV2(inValue);
            return retVal.Body.GetReceiptListECV2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EC_Endpoint_Client.ReceiptAgency.GetReceiptListECV2Response> EC_Endpoint_Client.ReceiptAgency.IReceiptAgencyExternalEC.GetReceiptListECV2Async(EC_Endpoint_Client.ReceiptAgency.GetReceiptListECV2Request request) {
            return base.Channel.GetReceiptListECV2Async(request);
        }
        
        public System.Threading.Tasks.Task<EC_Endpoint_Client.ReceiptAgency.GetReceiptListECV2Response> GetReceiptListECV2Async(string systemUserName, string systemPassword, EC_Endpoint_Client.ReceiptAgency.ReceiptType receiptTypeName, System.DateTime dateFrom, System.DateTime dateTo) {
            EC_Endpoint_Client.ReceiptAgency.GetReceiptListECV2Request inValue = new EC_Endpoint_Client.ReceiptAgency.GetReceiptListECV2Request();
            inValue.Body = new EC_Endpoint_Client.ReceiptAgency.GetReceiptListECV2RequestBody();
            inValue.Body.systemUserName = systemUserName;
            inValue.Body.systemPassword = systemPassword;
            inValue.Body.receiptTypeName = receiptTypeName;
            inValue.Body.dateFrom = dateFrom;
            inValue.Body.dateTo = dateTo;
            return ((EC_Endpoint_Client.ReceiptAgency.IReceiptAgencyExternalEC)(this)).GetReceiptListECV2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EC_Endpoint_Client.ReceiptAgency.SaveReceiptECResponse EC_Endpoint_Client.ReceiptAgency.IReceiptAgencyExternalEC.SaveReceiptEC(EC_Endpoint_Client.ReceiptAgency.SaveReceiptECRequest request) {
            return base.Channel.SaveReceiptEC(request);
        }
        
        public EC_Endpoint_Client.ReceiptAgency.ReceiptExternal SaveReceiptEC(string systemUserName, string systemPassword, EC_Endpoint_Client.ReceiptAgency.ReceiptSaveExternal receipt) {
            EC_Endpoint_Client.ReceiptAgency.SaveReceiptECRequest inValue = new EC_Endpoint_Client.ReceiptAgency.SaveReceiptECRequest();
            inValue.Body = new EC_Endpoint_Client.ReceiptAgency.SaveReceiptECRequestBody();
            inValue.Body.systemUserName = systemUserName;
            inValue.Body.systemPassword = systemPassword;
            inValue.Body.receipt = receipt;
            EC_Endpoint_Client.ReceiptAgency.SaveReceiptECResponse retVal = ((EC_Endpoint_Client.ReceiptAgency.IReceiptAgencyExternalEC)(this)).SaveReceiptEC(inValue);
            return retVal.Body.SaveReceiptECResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EC_Endpoint_Client.ReceiptAgency.SaveReceiptECResponse> EC_Endpoint_Client.ReceiptAgency.IReceiptAgencyExternalEC.SaveReceiptECAsync(EC_Endpoint_Client.ReceiptAgency.SaveReceiptECRequest request) {
            return base.Channel.SaveReceiptECAsync(request);
        }
        
        public System.Threading.Tasks.Task<EC_Endpoint_Client.ReceiptAgency.SaveReceiptECResponse> SaveReceiptECAsync(string systemUserName, string systemPassword, EC_Endpoint_Client.ReceiptAgency.ReceiptSaveExternal receipt) {
            EC_Endpoint_Client.ReceiptAgency.SaveReceiptECRequest inValue = new EC_Endpoint_Client.ReceiptAgency.SaveReceiptECRequest();
            inValue.Body = new EC_Endpoint_Client.ReceiptAgency.SaveReceiptECRequestBody();
            inValue.Body.systemUserName = systemUserName;
            inValue.Body.systemPassword = systemPassword;
            inValue.Body.receipt = receipt;
            return ((EC_Endpoint_Client.ReceiptAgency.IReceiptAgencyExternalEC)(this)).SaveReceiptECAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EC_Endpoint_Client.ReceiptAgency.UpdateReceiptECResponse EC_Endpoint_Client.ReceiptAgency.IReceiptAgencyExternalEC.UpdateReceiptEC(EC_Endpoint_Client.ReceiptAgency.UpdateReceiptECRequest request) {
            return base.Channel.UpdateReceiptEC(request);
        }
        
        public EC_Endpoint_Client.ReceiptAgency.Receipt UpdateReceiptEC(string systemUserName, string systemPassword, EC_Endpoint_Client.ReceiptAgency.ReceiptSaveExternal receipt) {
            EC_Endpoint_Client.ReceiptAgency.UpdateReceiptECRequest inValue = new EC_Endpoint_Client.ReceiptAgency.UpdateReceiptECRequest();
            inValue.Body = new EC_Endpoint_Client.ReceiptAgency.UpdateReceiptECRequestBody();
            inValue.Body.systemUserName = systemUserName;
            inValue.Body.systemPassword = systemPassword;
            inValue.Body.receipt = receipt;
            EC_Endpoint_Client.ReceiptAgency.UpdateReceiptECResponse retVal = ((EC_Endpoint_Client.ReceiptAgency.IReceiptAgencyExternalEC)(this)).UpdateReceiptEC(inValue);
            return retVal.Body.UpdateReceiptECResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EC_Endpoint_Client.ReceiptAgency.UpdateReceiptECResponse> EC_Endpoint_Client.ReceiptAgency.IReceiptAgencyExternalEC.UpdateReceiptECAsync(EC_Endpoint_Client.ReceiptAgency.UpdateReceiptECRequest request) {
            return base.Channel.UpdateReceiptECAsync(request);
        }
        
        public System.Threading.Tasks.Task<EC_Endpoint_Client.ReceiptAgency.UpdateReceiptECResponse> UpdateReceiptECAsync(string systemUserName, string systemPassword, EC_Endpoint_Client.ReceiptAgency.ReceiptSaveExternal receipt) {
            EC_Endpoint_Client.ReceiptAgency.UpdateReceiptECRequest inValue = new EC_Endpoint_Client.ReceiptAgency.UpdateReceiptECRequest();
            inValue.Body = new EC_Endpoint_Client.ReceiptAgency.UpdateReceiptECRequestBody();
            inValue.Body.systemUserName = systemUserName;
            inValue.Body.systemPassword = systemPassword;
            inValue.Body.receipt = receipt;
            return ((EC_Endpoint_Client.ReceiptAgency.IReceiptAgencyExternalEC)(this)).UpdateReceiptECAsync(inValue);
        }
    }
}
