//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC_Endpoint_Client.PrefillAgencyEC2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AltinnFault", Namespace="http://www.altinn.no/services/common/fault/2009/10")]
    [System.SerializableAttribute()]
    public partial class AltinnFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AltinnErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AltinnExtendedErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AltinnLocalizedErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AltinnErrorMessage {
            get {
                return this.AltinnErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.AltinnErrorMessageField, value) != true)) {
                    this.AltinnErrorMessageField = value;
                    this.RaisePropertyChanged("AltinnErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AltinnExtendedErrorMessage {
            get {
                return this.AltinnExtendedErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.AltinnExtendedErrorMessageField, value) != true)) {
                    this.AltinnExtendedErrorMessageField = value;
                    this.RaisePropertyChanged("AltinnExtendedErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AltinnLocalizedErrorMessage {
            get {
                return this.AltinnLocalizedErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.AltinnLocalizedErrorMessageField, value) != true)) {
                    this.AltinnLocalizedErrorMessageField = value;
                    this.RaisePropertyChanged("AltinnLocalizedErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorGuid {
            get {
                return this.ErrorGuidField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorGuidField, value) != true)) {
                    this.ErrorGuidField = value;
                    this.RaisePropertyChanged("ErrorGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorID {
            get {
                return this.ErrorIDField;
            }
            set {
                if ((this.ErrorIDField.Equals(value) != true)) {
                    this.ErrorIDField = value;
                    this.RaisePropertyChanged("ErrorID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserGuid {
            get {
                return this.UserGuidField;
            }
            set {
                if ((object.ReferenceEquals(this.UserGuidField, value) != true)) {
                    this.UserGuidField = value;
                    this.RaisePropertyChanged("UserGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIdField, value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PrefillFormTask", Namespace="http://schemas.altinn.no/services/ServiceEngine/PreFill/2009/10")]
    [System.SerializableAttribute()]
    public partial class PrefillFormTask : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ExternalServiceCodeField;
        
        private int ExternalServiceEditionCodeField;
        
        private string ExternalShipmentReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentityFieldHashCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid LargeInboundReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EC_Endpoint_Client.PrefillAgencyEC2.PrefillAttachmentBEList PreFillAttachmentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EC_Endpoint_Client.PrefillAgencyEC2.PrefillFormBEList PreFillFormsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EC_Endpoint_Client.PrefillAgencyEC2.PreFillIdentityFieldBEList PreFillIdentityFieldsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EC_Endpoint_Client.PrefillAgencyEC2.NotificationBEList PrefillNotificationsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiversReferenceField;
        
        private string ReporteeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SendersReferenceField;
        
        private string ServiceOwnerCodeField;
        
        private System.DateTime ValidFromDateField;
        
        private System.DateTime ValidToDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsReservableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ValidateButDoNotSendNotificationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ExternalServiceCode {
            get {
                return this.ExternalServiceCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ExternalServiceCodeField, value) != true)) {
                    this.ExternalServiceCodeField = value;
                    this.RaisePropertyChanged("ExternalServiceCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ExternalServiceEditionCode {
            get {
                return this.ExternalServiceEditionCodeField;
            }
            set {
                if ((this.ExternalServiceEditionCodeField.Equals(value) != true)) {
                    this.ExternalServiceEditionCodeField = value;
                    this.RaisePropertyChanged("ExternalServiceEditionCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ExternalShipmentReference {
            get {
                return this.ExternalShipmentReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.ExternalShipmentReferenceField, value) != true)) {
                    this.ExternalShipmentReferenceField = value;
                    this.RaisePropertyChanged("ExternalShipmentReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdentityFieldHashCode {
            get {
                return this.IdentityFieldHashCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentityFieldHashCodeField, value) != true)) {
                    this.IdentityFieldHashCodeField = value;
                    this.RaisePropertyChanged("IdentityFieldHashCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid LargeInboundReference {
            get {
                return this.LargeInboundReferenceField;
            }
            set {
                if ((this.LargeInboundReferenceField.Equals(value) != true)) {
                    this.LargeInboundReferenceField = value;
                    this.RaisePropertyChanged("LargeInboundReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EC_Endpoint_Client.PrefillAgencyEC2.PrefillAttachmentBEList PreFillAttachments {
            get {
                return this.PreFillAttachmentsField;
            }
            set {
                if ((object.ReferenceEquals(this.PreFillAttachmentsField, value) != true)) {
                    this.PreFillAttachmentsField = value;
                    this.RaisePropertyChanged("PreFillAttachments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EC_Endpoint_Client.PrefillAgencyEC2.PrefillFormBEList PreFillForms {
            get {
                return this.PreFillFormsField;
            }
            set {
                if ((object.ReferenceEquals(this.PreFillFormsField, value) != true)) {
                    this.PreFillFormsField = value;
                    this.RaisePropertyChanged("PreFillForms");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EC_Endpoint_Client.PrefillAgencyEC2.PreFillIdentityFieldBEList PreFillIdentityFields {
            get {
                return this.PreFillIdentityFieldsField;
            }
            set {
                if ((object.ReferenceEquals(this.PreFillIdentityFieldsField, value) != true)) {
                    this.PreFillIdentityFieldsField = value;
                    this.RaisePropertyChanged("PreFillIdentityFields");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EC_Endpoint_Client.PrefillAgencyEC2.NotificationBEList PrefillNotifications {
            get {
                return this.PrefillNotificationsField;
            }
            set {
                if ((object.ReferenceEquals(this.PrefillNotificationsField, value) != true)) {
                    this.PrefillNotificationsField = value;
                    this.RaisePropertyChanged("PrefillNotifications");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceiversReference {
            get {
                return this.ReceiversReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiversReferenceField, value) != true)) {
                    this.ReceiversReferenceField = value;
                    this.RaisePropertyChanged("ReceiversReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Reportee {
            get {
                return this.ReporteeField;
            }
            set {
                if ((object.ReferenceEquals(this.ReporteeField, value) != true)) {
                    this.ReporteeField = value;
                    this.RaisePropertyChanged("Reportee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SendersReference {
            get {
                return this.SendersReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.SendersReferenceField, value) != true)) {
                    this.SendersReferenceField = value;
                    this.RaisePropertyChanged("SendersReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ServiceOwnerCode {
            get {
                return this.ServiceOwnerCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceOwnerCodeField, value) != true)) {
                    this.ServiceOwnerCodeField = value;
                    this.RaisePropertyChanged("ServiceOwnerCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime ValidFromDate {
            get {
                return this.ValidFromDateField;
            }
            set {
                if ((this.ValidFromDateField.Equals(value) != true)) {
                    this.ValidFromDateField = value;
                    this.RaisePropertyChanged("ValidFromDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime ValidToDate {
            get {
                return this.ValidToDateField;
            }
            set {
                if ((this.ValidToDateField.Equals(value) != true)) {
                    this.ValidToDateField = value;
                    this.RaisePropertyChanged("ValidToDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public System.Nullable<bool> IsReservable {
            get {
                return this.IsReservableField;
            }
            set {
                if ((this.IsReservableField.Equals(value) != true)) {
                    this.IsReservableField = value;
                    this.RaisePropertyChanged("IsReservable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=16)]
        public bool ValidateButDoNotSendNotification {
            get {
                return this.ValidateButDoNotSendNotificationField;
            }
            set {
                if ((this.ValidateButDoNotSendNotificationField.Equals(value) != true)) {
                    this.ValidateButDoNotSendNotificationField = value;
                    this.RaisePropertyChanged("ValidateButDoNotSendNotification");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="PrefillAttachmentBEList", Namespace="http://schemas.altinn.no/services/ServiceEngine/PreFill/2009/10", ItemName="PrefillFormTaskAttachment")]
    [System.SerializableAttribute()]
    public class PrefillAttachmentBEList : System.Collections.Generic.List<EC_Endpoint_Client.PrefillAgencyEC2.PrefillFormTaskAttachment> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="PrefillFormBEList", Namespace="http://schemas.altinn.no/services/ServiceEngine/PreFill/2009/10", ItemName="PrefillForm")]
    [System.SerializableAttribute()]
    public class PrefillFormBEList : System.Collections.Generic.List<EC_Endpoint_Client.PrefillAgencyEC2.PrefillForm> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="PreFillIdentityFieldBEList", Namespace="http://schemas.altinn.no/services/ServiceEngine/PreFill/2009/10", ItemName="PreFillIdentityFieldBE")]
    [System.SerializableAttribute()]
    public class PreFillIdentityFieldBEList : System.Collections.Generic.List<EC_Endpoint_Client.PrefillAgencyEC2.PreFillIdentityFieldBE> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="NotificationBEList", Namespace="http://schemas.altinn.no/services/ServiceEngine/Notification/2009/10", ItemName="Notification")]
    [System.SerializableAttribute()]
    public class NotificationBEList : System.Collections.Generic.List<EC_Endpoint_Client.PrefillAgencyEC2.Notification> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PrefillFormTaskAttachment", Namespace="http://schemas.altinn.no/services/ServiceEngine/PreFill/2009/10")]
    [System.SerializableAttribute()]
    public partial class PrefillFormTaskAttachment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private byte[] AttachmentDataField;
        
        private string AttachmentNameField;
        
        private EC_Endpoint_Client.PrefillAgencyEC2.AttachmentType AttachmentTypeField;
        
        private string FileNameField;
        
        private string SendersReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> SignedByDefaultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> SigningLockedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public byte[] AttachmentData {
            get {
                return this.AttachmentDataField;
            }
            set {
                if ((object.ReferenceEquals(this.AttachmentDataField, value) != true)) {
                    this.AttachmentDataField = value;
                    this.RaisePropertyChanged("AttachmentData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string AttachmentName {
            get {
                return this.AttachmentNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AttachmentNameField, value) != true)) {
                    this.AttachmentNameField = value;
                    this.RaisePropertyChanged("AttachmentName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public EC_Endpoint_Client.PrefillAgencyEC2.AttachmentType AttachmentType {
            get {
                return this.AttachmentTypeField;
            }
            set {
                if ((this.AttachmentTypeField.Equals(value) != true)) {
                    this.AttachmentTypeField = value;
                    this.RaisePropertyChanged("AttachmentType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string SendersReference {
            get {
                return this.SendersReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.SendersReferenceField, value) != true)) {
                    this.SendersReferenceField = value;
                    this.RaisePropertyChanged("SendersReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> SignedByDefault {
            get {
                return this.SignedByDefaultField;
            }
            set {
                if ((this.SignedByDefaultField.Equals(value) != true)) {
                    this.SignedByDefaultField = value;
                    this.RaisePropertyChanged("SignedByDefault");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> SigningLocked {
            get {
                return this.SigningLockedField;
            }
            set {
                if ((this.SigningLockedField.Equals(value) != true)) {
                    this.SigningLockedField = value;
                    this.RaisePropertyChanged("SigningLocked");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AttachmentType", Namespace="http://schemas.altinn.no/services/serviceEntity/2009/10")]
    public enum AttachmentType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        application_None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        application_pdf = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        application_msword = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        application_vnd_ms_excel = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        application_vnd_oasis_opendocument_text = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        application_vnd_oasis_opendocument_presentation = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        application_vnd_oasis_opendocument_spreadsheet = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        application_rtf = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        application_vnd_ms_powerpoint = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        application_postscript = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        application_zip = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        text_plain = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        text_html = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        text_xml = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        text_rtf = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        text_richtext = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        binary_octet_stream = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        not_Applicable = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MTOM = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BASE64 = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        image_jpeg = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        image_gif = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        image_bmp = 22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        formtask_pdf = 23,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PrefillForm", Namespace="http://schemas.altinn.no/services/ServiceEngine/PreFill/2009/10")]
    [System.SerializableAttribute()]
    public partial class PrefillForm : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DataFormatIDField;
        
        private int DataFormatVersionField;
        
        private string FormDataXMLField;
        
        private string SendersReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> SignedByDefaultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> SigningLockedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string DataFormatID {
            get {
                return this.DataFormatIDField;
            }
            set {
                if ((object.ReferenceEquals(this.DataFormatIDField, value) != true)) {
                    this.DataFormatIDField = value;
                    this.RaisePropertyChanged("DataFormatID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int DataFormatVersion {
            get {
                return this.DataFormatVersionField;
            }
            set {
                if ((this.DataFormatVersionField.Equals(value) != true)) {
                    this.DataFormatVersionField = value;
                    this.RaisePropertyChanged("DataFormatVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string FormDataXML {
            get {
                return this.FormDataXMLField;
            }
            set {
                if ((object.ReferenceEquals(this.FormDataXMLField, value) != true)) {
                    this.FormDataXMLField = value;
                    this.RaisePropertyChanged("FormDataXML");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string SendersReference {
            get {
                return this.SendersReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.SendersReferenceField, value) != true)) {
                    this.SendersReferenceField = value;
                    this.RaisePropertyChanged("SendersReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> SignedByDefault {
            get {
                return this.SignedByDefaultField;
            }
            set {
                if ((this.SignedByDefaultField.Equals(value) != true)) {
                    this.SignedByDefaultField = value;
                    this.RaisePropertyChanged("SignedByDefault");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> SigningLocked {
            get {
                return this.SigningLockedField;
            }
            set {
                if ((this.SigningLockedField.Equals(value) != true)) {
                    this.SigningLockedField = value;
                    this.RaisePropertyChanged("SigningLocked");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PreFillIdentityFieldBE", Namespace="http://schemas.altinn.no/services/ServiceEngine/PreFill/2009/10")]
    [System.SerializableAttribute()]
    public partial class PreFillIdentityFieldBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FieldValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IndexField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FieldValue {
            get {
                return this.FieldValueField;
            }
            set {
                if ((object.ReferenceEquals(this.FieldValueField, value) != true)) {
                    this.FieldValueField = value;
                    this.RaisePropertyChanged("FieldValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Index {
            get {
                return this.IndexField;
            }
            set {
                if ((object.ReferenceEquals(this.IndexField, value) != true)) {
                    this.IndexField = value;
                    this.RaisePropertyChanged("Index");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Notification", Namespace="http://schemas.altinn.no/services/ServiceEngine/Notification/2009/10")]
    [System.SerializableAttribute()]
    public partial class Notification : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FromAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NotificationIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EC_Endpoint_Client.PrefillAgencyEC2.NotificationType NotifyTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReporteeElementIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ReporteeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ShipmentDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LanguageCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NotificationTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EC_Endpoint_Client.PrefillAgencyEC2.TextTokenSubstitutionBEList TextTokensField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EC_Endpoint_Client.PrefillAgencyEC2.ReceiverEndPointBEList ReceiverEndPointsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FromAddress {
            get {
                return this.FromAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.FromAddressField, value) != true)) {
                    this.FromAddressField = value;
                    this.RaisePropertyChanged("FromAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NotificationID {
            get {
                return this.NotificationIDField;
            }
            set {
                if ((this.NotificationIDField.Equals(value) != true)) {
                    this.NotificationIDField = value;
                    this.RaisePropertyChanged("NotificationID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EC_Endpoint_Client.PrefillAgencyEC2.NotificationType NotifyType {
            get {
                return this.NotifyTypeField;
            }
            set {
                if ((this.NotifyTypeField.Equals(value) != true)) {
                    this.NotifyTypeField = value;
                    this.RaisePropertyChanged("NotifyType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReporteeElementID {
            get {
                return this.ReporteeElementIDField;
            }
            set {
                if ((this.ReporteeElementIDField.Equals(value) != true)) {
                    this.ReporteeElementIDField = value;
                    this.RaisePropertyChanged("ReporteeElementID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ReporteeId {
            get {
                return this.ReporteeIdField;
            }
            set {
                if ((this.ReporteeIdField.Equals(value) != true)) {
                    this.ReporteeIdField = value;
                    this.RaisePropertyChanged("ReporteeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ShipmentDateTime {
            get {
                return this.ShipmentDateTimeField;
            }
            set {
                if ((this.ShipmentDateTimeField.Equals(value) != true)) {
                    this.ShipmentDateTimeField = value;
                    this.RaisePropertyChanged("ShipmentDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string LanguageCode {
            get {
                return this.LanguageCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.LanguageCodeField, value) != true)) {
                    this.LanguageCodeField = value;
                    this.RaisePropertyChanged("LanguageCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string NotificationType {
            get {
                return this.NotificationTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.NotificationTypeField, value) != true)) {
                    this.NotificationTypeField = value;
                    this.RaisePropertyChanged("NotificationType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public EC_Endpoint_Client.PrefillAgencyEC2.TextTokenSubstitutionBEList TextTokens {
            get {
                return this.TextTokensField;
            }
            set {
                if ((object.ReferenceEquals(this.TextTokensField, value) != true)) {
                    this.TextTokensField = value;
                    this.RaisePropertyChanged("TextTokens");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public EC_Endpoint_Client.PrefillAgencyEC2.ReceiverEndPointBEList ReceiverEndPoints {
            get {
                return this.ReceiverEndPointsField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiverEndPointsField, value) != true)) {
                    this.ReceiverEndPointsField = value;
                    this.RaisePropertyChanged("ReceiverEndPoints");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NotificationType", Namespace="http://schemas.altinn.no/services/Intermediary/Notification/2009/10")]
    public enum NotificationType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PIN = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Correspondence = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PreFill = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        StandAlone = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        General = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="TextTokenSubstitutionBEList", Namespace="http://schemas.altinn.no/services/ServiceEngine/Notification/2009/10", ItemName="TextToken")]
    [System.SerializableAttribute()]
    public class TextTokenSubstitutionBEList : System.Collections.Generic.List<EC_Endpoint_Client.PrefillAgencyEC2.TextToken> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ReceiverEndPointBEList", Namespace="http://schemas.altinn.no/services/ServiceEngine/Notification/2009/10", ItemName="ReceiverEndPoint")]
    [System.SerializableAttribute()]
    public class ReceiverEndPointBEList : System.Collections.Generic.List<EC_Endpoint_Client.PrefillAgencyEC2.ReceiverEndPoint> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TextToken", Namespace="http://schemas.altinn.no/services/ServiceEngine/Notification/2009/10")]
    [System.SerializableAttribute()]
    public partial class TextToken : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TokenNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TokenNum {
            get {
                return this.TokenNumField;
            }
            set {
                if ((this.TokenNumField.Equals(value) != true)) {
                    this.TokenNumField = value;
                    this.RaisePropertyChanged("TokenNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TokenValue {
            get {
                return this.TokenValueField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenValueField, value) != true)) {
                    this.TokenValueField = value;
                    this.RaisePropertyChanged("TokenValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReceiverEndPoint", Namespace="http://schemas.altinn.no/services/ServiceEngine/Notification/2009/10")]
    [System.SerializableAttribute()]
    public partial class ReceiverEndPoint : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<EC_Endpoint_Client.PrefillAgencyEC2.TransportType> TransportTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiverAddressField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<EC_Endpoint_Client.PrefillAgencyEC2.TransportType> TransportType {
            get {
                return this.TransportTypeField;
            }
            set {
                if ((this.TransportTypeField.Equals(value) != true)) {
                    this.TransportTypeField = value;
                    this.RaisePropertyChanged("TransportType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string ReceiverAddress {
            get {
                return this.ReceiverAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiverAddressField, value) != true)) {
                    this.ReceiverAddressField = value;
                    this.RaisePropertyChanged("ReceiverAddress");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransportType", Namespace="http://schemas.altinn.no/serviceengine/formsengine/2009/10")]
    public enum TransportType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SMS = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Email = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IM = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Both = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SMSPreferred = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EmailPreferred = 6,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReceiptExternal", Namespace="http://schemas.altinn.no/services/Intermediary/Receipt/2009/10")]
    [System.SerializableAttribute()]
    public partial class ReceiptExternal : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastChangedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ParentReceiptIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiptHistoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReceiptIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EC_Endpoint_Client.PrefillAgencyEC2.ReceiptStatusEnum ReceiptStatusCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiptTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EC_Endpoint_Client.PrefillAgencyEC2.ReceiptTypeEnum ReceiptTypeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EC_Endpoint_Client.PrefillAgencyEC2.ReferenceList ReferencesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EC_Endpoint_Client.PrefillAgencyEC2.ReceiptExternalList SubReceiptsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastChanged {
            get {
                return this.LastChangedField;
            }
            set {
                if ((this.LastChangedField.Equals(value) != true)) {
                    this.LastChangedField = value;
                    this.RaisePropertyChanged("LastChanged");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ParentReceiptId {
            get {
                return this.ParentReceiptIdField;
            }
            set {
                if ((this.ParentReceiptIdField.Equals(value) != true)) {
                    this.ParentReceiptIdField = value;
                    this.RaisePropertyChanged("ParentReceiptId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceiptHistory {
            get {
                return this.ReceiptHistoryField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiptHistoryField, value) != true)) {
                    this.ReceiptHistoryField = value;
                    this.RaisePropertyChanged("ReceiptHistory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReceiptId {
            get {
                return this.ReceiptIdField;
            }
            set {
                if ((this.ReceiptIdField.Equals(value) != true)) {
                    this.ReceiptIdField = value;
                    this.RaisePropertyChanged("ReceiptId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EC_Endpoint_Client.PrefillAgencyEC2.ReceiptStatusEnum ReceiptStatusCode {
            get {
                return this.ReceiptStatusCodeField;
            }
            set {
                if ((this.ReceiptStatusCodeField.Equals(value) != true)) {
                    this.ReceiptStatusCodeField = value;
                    this.RaisePropertyChanged("ReceiptStatusCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceiptText {
            get {
                return this.ReceiptTextField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiptTextField, value) != true)) {
                    this.ReceiptTextField = value;
                    this.RaisePropertyChanged("ReceiptText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EC_Endpoint_Client.PrefillAgencyEC2.ReceiptTypeEnum ReceiptTypeName {
            get {
                return this.ReceiptTypeNameField;
            }
            set {
                if ((this.ReceiptTypeNameField.Equals(value) != true)) {
                    this.ReceiptTypeNameField = value;
                    this.RaisePropertyChanged("ReceiptTypeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EC_Endpoint_Client.PrefillAgencyEC2.ReferenceList References {
            get {
                return this.ReferencesField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferencesField, value) != true)) {
                    this.ReferencesField = value;
                    this.RaisePropertyChanged("References");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EC_Endpoint_Client.PrefillAgencyEC2.ReceiptExternalList SubReceipts {
            get {
                return this.SubReceiptsField;
            }
            set {
                if ((object.ReferenceEquals(this.SubReceiptsField, value) != true)) {
                    this.SubReceiptsField = value;
                    this.RaisePropertyChanged("SubReceipts");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReceiptStatusEnum", Namespace="http://schemas.altinn.no/services/Intermediary/Receipt/2009/10")]
    public enum ReceiptStatusEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotSet = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OK = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnExpectedError = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ValidationFailed = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rejected = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReceiptTypeEnum", Namespace="http://schemas.altinn.no/services/Intermediary/Receipt/2009/10")]
    public enum ReceiptTypeEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotSet = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FormTask = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Correspondence = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PINCODE = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Subscription = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Outbound = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PreFill = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegisterDLS = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegisterDSF = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegisterER = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegisterDSFProperty = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegisterDSFStreet = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegisterDSFCountry = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegisterDSFUser = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LookUp = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegisterDSFStreetAdd = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RegisterDSFPropertyAdd = 16,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ReferenceList", Namespace="http://schemas.altinn.no/services/Intermediary/Receipt/2009/10", ItemName="Reference")]
    [System.SerializableAttribute()]
    public class ReferenceList : System.Collections.Generic.List<EC_Endpoint_Client.PrefillAgencyEC2.Reference> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ReceiptExternalList", Namespace="http://schemas.altinn.no/services/Intermediary/Receipt/2009/10", ItemName="ReceiptExternal")]
    [System.SerializableAttribute()]
    public class ReceiptExternalList : System.Collections.Generic.List<EC_Endpoint_Client.PrefillAgencyEC2.ReceiptExternal> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Reference", Namespace="http://schemas.altinn.no/services/Intermediary/Receipt/2009/10")]
    [System.SerializableAttribute()]
    public partial class Reference : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EC_Endpoint_Client.PrefillAgencyEC2.ReferenceType ReferenceTypeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferenceValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EC_Endpoint_Client.PrefillAgencyEC2.ReferenceType ReferenceTypeName {
            get {
                return this.ReferenceTypeNameField;
            }
            set {
                if ((this.ReferenceTypeNameField.Equals(value) != true)) {
                    this.ReferenceTypeNameField = value;
                    this.RaisePropertyChanged("ReferenceTypeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReferenceValue {
            get {
                return this.ReferenceValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenceValueField, value) != true)) {
                    this.ReferenceValueField = value;
                    this.RaisePropertyChanged("ReferenceValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReferenceType", Namespace="http://schemas.altinn.no/services/Intermediary/Shipment/2009/10")]
    public enum ReferenceType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotSet = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ExternalShipmentReference = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EndUserSystemReference = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ParentReference = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SendersReference = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WorkFlowReference = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BatchReference = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OutboundShipmentReference = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ReceiversReference = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Altinn1Reference = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OwnerPartyReference = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PartyReference = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ArchiveReference = 12,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PrefillFormTaskDetails", Namespace="http://schemas.altinn.no/services/ServiceEngine/PreFill/2009/10")]
    [System.SerializableAttribute()]
    public partial class PrefillFormTaskDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EC_Endpoint_Client.PrefillAgencyEC2.PreFillFormTaskBEList PreFillFormTasklistField;
        
        private string SystemUserCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EC_Endpoint_Client.PrefillAgencyEC2.PreFillFormTaskBEList PreFillFormTasklist {
            get {
                return this.PreFillFormTasklistField;
            }
            set {
                if ((object.ReferenceEquals(this.PreFillFormTasklistField, value) != true)) {
                    this.PreFillFormTasklistField = value;
                    this.RaisePropertyChanged("PreFillFormTasklist");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string SystemUserCode {
            get {
                return this.SystemUserCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SystemUserCodeField, value) != true)) {
                    this.SystemUserCodeField = value;
                    this.RaisePropertyChanged("SystemUserCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="PreFillFormTaskBEList", Namespace="http://schemas.altinn.no/services/ServiceEngine/PreFill/2009/10", ItemName="PrefillFormTask")]
    [System.SerializableAttribute()]
    public class PreFillFormTaskBEList : System.Collections.Generic.List<EC_Endpoint_Client.PrefillAgencyEC2.PrefillFormTask> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.altinn.no/services/ServiceEngine/PreFill/2010/10", ConfigurationName="PrefillAgencyEC2.IPreFillAgencyExternalEC2")]
    public interface IPreFillAgencyExternalEC2 {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://www.altinn.no/services/2009/10) of message TestRequest does not match the default value (http://www.altinn.no/services/ServiceEngine/PreFill/2010/10)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/2009/10/IAltinnContractBase/Test", ReplyAction="http://www.altinn.no/services/2009/10/IAltinnContractBase/TestResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EC_Endpoint_Client.PrefillAgencyEC2.AltinnFault), Action="http://www.altinn.no/services/2009/10/IAltinnContractBase/TestAltinnFaultFault", Name="AltinnFault", Namespace="http://www.altinn.no/services/common/fault/2009/10")]
        EC_Endpoint_Client.PrefillAgencyEC2.TestResponse Test(EC_Endpoint_Client.PrefillAgencyEC2.TestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/2009/10/IAltinnContractBase/Test", ReplyAction="http://www.altinn.no/services/2009/10/IAltinnContractBase/TestResponse")]
        System.Threading.Tasks.Task<EC_Endpoint_Client.PrefillAgencyEC2.TestResponse> TestAsync(EC_Endpoint_Client.PrefillAgencyEC2.TestRequest request);
        
        // CODEGEN: Generating message contract since element name systemUserName from namespace http://www.altinn.no/services/ServiceEngine/PreFill/2010/10 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/ServiceEngine/PreFill/2010/10/IPreFillAgencyExterna" +
            "lEC/SubmitAndInstantiatePrefilledFormTaskEC", ReplyAction="http://www.altinn.no/services/ServiceEngine/PreFill/2010/10/IPreFillAgencyExterna" +
            "lEC/SubmitAndInstantiatePrefilledFormTaskECResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EC_Endpoint_Client.PrefillAgencyEC2.AltinnFault), Action="http://www.altinn.no/services/ServiceEngine/PreFill/2010/10/IPreFillAgencyExterna" +
            "lEC/SubmitAndInstantiatePrefilledFormTaskECAltinnFaultFault", Name="AltinnFault", Namespace="http://www.altinn.no/services/common/fault/2009/10")]
        EC_Endpoint_Client.PrefillAgencyEC2.SubmitAndInstantiatePrefilledFormTaskECResponse SubmitAndInstantiatePrefilledFormTaskEC(EC_Endpoint_Client.PrefillAgencyEC2.SubmitAndInstantiatePrefilledFormTaskECRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/ServiceEngine/PreFill/2010/10/IPreFillAgencyExterna" +
            "lEC/SubmitAndInstantiatePrefilledFormTaskEC", ReplyAction="http://www.altinn.no/services/ServiceEngine/PreFill/2010/10/IPreFillAgencyExterna" +
            "lEC/SubmitAndInstantiatePrefilledFormTaskECResponse")]
        System.Threading.Tasks.Task<EC_Endpoint_Client.PrefillAgencyEC2.SubmitAndInstantiatePrefilledFormTaskECResponse> SubmitAndInstantiatePrefilledFormTaskECAsync(EC_Endpoint_Client.PrefillAgencyEC2.SubmitAndInstantiatePrefilledFormTaskECRequest request);
        
        // CODEGEN: Generating message contract since element name systemUserName from namespace http://www.altinn.no/services/ServiceEngine/PreFill/2010/10 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/ServiceEngine/PreFill/2010/10/IPreFillAgencyExterna" +
            "lEC/SubmitPrefilledFormTasksEC", ReplyAction="http://www.altinn.no/services/ServiceEngine/PreFill/2010/10/IPreFillAgencyExterna" +
            "lEC/SubmitPrefilledFormTasksECResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EC_Endpoint_Client.PrefillAgencyEC2.AltinnFault), Action="http://www.altinn.no/services/ServiceEngine/PreFill/2010/10/IPreFillAgencyExterna" +
            "lEC/SubmitPrefilledFormTasksECAltinnFaultFault", Name="AltinnFault", Namespace="http://www.altinn.no/services/common/fault/2009/10")]
        EC_Endpoint_Client.PrefillAgencyEC2.SubmitPrefilledFormTasksECResponse SubmitPrefilledFormTasksEC(EC_Endpoint_Client.PrefillAgencyEC2.SubmitPrefilledFormTasksECRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/ServiceEngine/PreFill/2010/10/IPreFillAgencyExterna" +
            "lEC/SubmitPrefilledFormTasksEC", ReplyAction="http://www.altinn.no/services/ServiceEngine/PreFill/2010/10/IPreFillAgencyExterna" +
            "lEC/SubmitPrefilledFormTasksECResponse")]
        System.Threading.Tasks.Task<EC_Endpoint_Client.PrefillAgencyEC2.SubmitPrefilledFormTasksECResponse> SubmitPrefilledFormTasksECAsync(EC_Endpoint_Client.PrefillAgencyEC2.SubmitPrefilledFormTasksECRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Test", WrapperNamespace="http://www.altinn.no/services/2009/10", IsWrapped=true)]
    public partial class TestRequest {
        
        public TestRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TestResponse", WrapperNamespace="http://www.altinn.no/services/2009/10", IsWrapped=true)]
    public partial class TestResponse {
        
        public TestResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitAndInstantiatePrefilledFormTaskECRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubmitAndInstantiatePrefilledFormTaskEC", Namespace="http://www.altinn.no/services/ServiceEngine/PreFill/2010/10", Order=0)]
        public EC_Endpoint_Client.PrefillAgencyEC2.SubmitAndInstantiatePrefilledFormTaskECRequestBody Body;
        
        public SubmitAndInstantiatePrefilledFormTaskECRequest() {
        }
        
        public SubmitAndInstantiatePrefilledFormTaskECRequest(EC_Endpoint_Client.PrefillAgencyEC2.SubmitAndInstantiatePrefilledFormTaskECRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.altinn.no/services/ServiceEngine/PreFill/2010/10")]
    public partial class SubmitAndInstantiatePrefilledFormTaskECRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string systemUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string systemPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string externalBatchId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public EC_Endpoint_Client.PrefillAgencyEC2.PrefillFormTask preFillFormTask;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public bool doSaveFormTask;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool doinstantiateFormTask;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public System.Nullable<int> caseId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public System.Nullable<System.DateTime> dueDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string instantitedOnBehalfOf;
        
        public SubmitAndInstantiatePrefilledFormTaskECRequestBody() {
        }
        
        public SubmitAndInstantiatePrefilledFormTaskECRequestBody(string systemUserName, string systemPassword, string externalBatchId, EC_Endpoint_Client.PrefillAgencyEC2.PrefillFormTask preFillFormTask, bool doSaveFormTask, bool doinstantiateFormTask, System.Nullable<int> caseId, System.Nullable<System.DateTime> dueDate, string instantitedOnBehalfOf) {
            this.systemUserName = systemUserName;
            this.systemPassword = systemPassword;
            this.externalBatchId = externalBatchId;
            this.preFillFormTask = preFillFormTask;
            this.doSaveFormTask = doSaveFormTask;
            this.doinstantiateFormTask = doinstantiateFormTask;
            this.caseId = caseId;
            this.dueDate = dueDate;
            this.instantitedOnBehalfOf = instantitedOnBehalfOf;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitAndInstantiatePrefilledFormTaskECResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubmitAndInstantiatePrefilledFormTaskECResponse", Namespace="http://www.altinn.no/services/ServiceEngine/PreFill/2010/10", Order=0)]
        public EC_Endpoint_Client.PrefillAgencyEC2.SubmitAndInstantiatePrefilledFormTaskECResponseBody Body;
        
        public SubmitAndInstantiatePrefilledFormTaskECResponse() {
        }
        
        public SubmitAndInstantiatePrefilledFormTaskECResponse(EC_Endpoint_Client.PrefillAgencyEC2.SubmitAndInstantiatePrefilledFormTaskECResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.altinn.no/services/ServiceEngine/PreFill/2010/10")]
    public partial class SubmitAndInstantiatePrefilledFormTaskECResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public EC_Endpoint_Client.PrefillAgencyEC2.ReceiptExternal SubmitAndInstantiatePrefilledFormTaskECResult;
        
        public SubmitAndInstantiatePrefilledFormTaskECResponseBody() {
        }
        
        public SubmitAndInstantiatePrefilledFormTaskECResponseBody(EC_Endpoint_Client.PrefillAgencyEC2.ReceiptExternal SubmitAndInstantiatePrefilledFormTaskECResult) {
            this.SubmitAndInstantiatePrefilledFormTaskECResult = SubmitAndInstantiatePrefilledFormTaskECResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitPrefilledFormTasksECRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubmitPrefilledFormTasksEC", Namespace="http://www.altinn.no/services/ServiceEngine/PreFill/2010/10", Order=0)]
        public EC_Endpoint_Client.PrefillAgencyEC2.SubmitPrefilledFormTasksECRequestBody Body;
        
        public SubmitPrefilledFormTasksECRequest() {
        }
        
        public SubmitPrefilledFormTasksECRequest(EC_Endpoint_Client.PrefillAgencyEC2.SubmitPrefilledFormTasksECRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.altinn.no/services/ServiceEngine/PreFill/2010/10")]
    public partial class SubmitPrefilledFormTasksECRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string systemUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string systemPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string externalBatchId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public EC_Endpoint_Client.PrefillAgencyEC2.PrefillFormTaskDetails preFillFormTasksDetails;
        
        public SubmitPrefilledFormTasksECRequestBody() {
        }
        
        public SubmitPrefilledFormTasksECRequestBody(string systemUserName, string systemPassword, string externalBatchId, EC_Endpoint_Client.PrefillAgencyEC2.PrefillFormTaskDetails preFillFormTasksDetails) {
            this.systemUserName = systemUserName;
            this.systemPassword = systemPassword;
            this.externalBatchId = externalBatchId;
            this.preFillFormTasksDetails = preFillFormTasksDetails;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitPrefilledFormTasksECResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubmitPrefilledFormTasksECResponse", Namespace="http://www.altinn.no/services/ServiceEngine/PreFill/2010/10", Order=0)]
        public EC_Endpoint_Client.PrefillAgencyEC2.SubmitPrefilledFormTasksECResponseBody Body;
        
        public SubmitPrefilledFormTasksECResponse() {
        }
        
        public SubmitPrefilledFormTasksECResponse(EC_Endpoint_Client.PrefillAgencyEC2.SubmitPrefilledFormTasksECResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.altinn.no/services/ServiceEngine/PreFill/2010/10")]
    public partial class SubmitPrefilledFormTasksECResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public EC_Endpoint_Client.PrefillAgencyEC2.ReceiptExternal SubmitPrefilledFormTasksECResult;
        
        public SubmitPrefilledFormTasksECResponseBody() {
        }
        
        public SubmitPrefilledFormTasksECResponseBody(EC_Endpoint_Client.PrefillAgencyEC2.ReceiptExternal SubmitPrefilledFormTasksECResult) {
            this.SubmitPrefilledFormTasksECResult = SubmitPrefilledFormTasksECResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPreFillAgencyExternalEC2Channel : EC_Endpoint_Client.PrefillAgencyEC2.IPreFillAgencyExternalEC2, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PreFillAgencyExternalEC2Client : System.ServiceModel.ClientBase<EC_Endpoint_Client.PrefillAgencyEC2.IPreFillAgencyExternalEC2>, EC_Endpoint_Client.PrefillAgencyEC2.IPreFillAgencyExternalEC2 {
        
        public PreFillAgencyExternalEC2Client() {
        }
        
        public PreFillAgencyExternalEC2Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PreFillAgencyExternalEC2Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PreFillAgencyExternalEC2Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PreFillAgencyExternalEC2Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EC_Endpoint_Client.PrefillAgencyEC2.TestResponse EC_Endpoint_Client.PrefillAgencyEC2.IPreFillAgencyExternalEC2.Test(EC_Endpoint_Client.PrefillAgencyEC2.TestRequest request) {
            return base.Channel.Test(request);
        }
        
        public void Test() {
            EC_Endpoint_Client.PrefillAgencyEC2.TestRequest inValue = new EC_Endpoint_Client.PrefillAgencyEC2.TestRequest();
            EC_Endpoint_Client.PrefillAgencyEC2.TestResponse retVal = ((EC_Endpoint_Client.PrefillAgencyEC2.IPreFillAgencyExternalEC2)(this)).Test(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EC_Endpoint_Client.PrefillAgencyEC2.TestResponse> EC_Endpoint_Client.PrefillAgencyEC2.IPreFillAgencyExternalEC2.TestAsync(EC_Endpoint_Client.PrefillAgencyEC2.TestRequest request) {
            return base.Channel.TestAsync(request);
        }
        
        public System.Threading.Tasks.Task<EC_Endpoint_Client.PrefillAgencyEC2.TestResponse> TestAsync() {
            EC_Endpoint_Client.PrefillAgencyEC2.TestRequest inValue = new EC_Endpoint_Client.PrefillAgencyEC2.TestRequest();
            return ((EC_Endpoint_Client.PrefillAgencyEC2.IPreFillAgencyExternalEC2)(this)).TestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EC_Endpoint_Client.PrefillAgencyEC2.SubmitAndInstantiatePrefilledFormTaskECResponse EC_Endpoint_Client.PrefillAgencyEC2.IPreFillAgencyExternalEC2.SubmitAndInstantiatePrefilledFormTaskEC(EC_Endpoint_Client.PrefillAgencyEC2.SubmitAndInstantiatePrefilledFormTaskECRequest request) {
            return base.Channel.SubmitAndInstantiatePrefilledFormTaskEC(request);
        }
        
        public EC_Endpoint_Client.PrefillAgencyEC2.ReceiptExternal SubmitAndInstantiatePrefilledFormTaskEC(string systemUserName, string systemPassword, string externalBatchId, EC_Endpoint_Client.PrefillAgencyEC2.PrefillFormTask preFillFormTask, bool doSaveFormTask, bool doinstantiateFormTask, System.Nullable<int> caseId, System.Nullable<System.DateTime> dueDate, string instantitedOnBehalfOf) {
            EC_Endpoint_Client.PrefillAgencyEC2.SubmitAndInstantiatePrefilledFormTaskECRequest inValue = new EC_Endpoint_Client.PrefillAgencyEC2.SubmitAndInstantiatePrefilledFormTaskECRequest();
            inValue.Body = new EC_Endpoint_Client.PrefillAgencyEC2.SubmitAndInstantiatePrefilledFormTaskECRequestBody();
            inValue.Body.systemUserName = systemUserName;
            inValue.Body.systemPassword = systemPassword;
            inValue.Body.externalBatchId = externalBatchId;
            inValue.Body.preFillFormTask = preFillFormTask;
            inValue.Body.doSaveFormTask = doSaveFormTask;
            inValue.Body.doinstantiateFormTask = doinstantiateFormTask;
            inValue.Body.caseId = caseId;
            inValue.Body.dueDate = dueDate;
            inValue.Body.instantitedOnBehalfOf = instantitedOnBehalfOf;
            EC_Endpoint_Client.PrefillAgencyEC2.SubmitAndInstantiatePrefilledFormTaskECResponse retVal = ((EC_Endpoint_Client.PrefillAgencyEC2.IPreFillAgencyExternalEC2)(this)).SubmitAndInstantiatePrefilledFormTaskEC(inValue);
            return retVal.Body.SubmitAndInstantiatePrefilledFormTaskECResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EC_Endpoint_Client.PrefillAgencyEC2.SubmitAndInstantiatePrefilledFormTaskECResponse> EC_Endpoint_Client.PrefillAgencyEC2.IPreFillAgencyExternalEC2.SubmitAndInstantiatePrefilledFormTaskECAsync(EC_Endpoint_Client.PrefillAgencyEC2.SubmitAndInstantiatePrefilledFormTaskECRequest request) {
            return base.Channel.SubmitAndInstantiatePrefilledFormTaskECAsync(request);
        }
        
        public System.Threading.Tasks.Task<EC_Endpoint_Client.PrefillAgencyEC2.SubmitAndInstantiatePrefilledFormTaskECResponse> SubmitAndInstantiatePrefilledFormTaskECAsync(string systemUserName, string systemPassword, string externalBatchId, EC_Endpoint_Client.PrefillAgencyEC2.PrefillFormTask preFillFormTask, bool doSaveFormTask, bool doinstantiateFormTask, System.Nullable<int> caseId, System.Nullable<System.DateTime> dueDate, string instantitedOnBehalfOf) {
            EC_Endpoint_Client.PrefillAgencyEC2.SubmitAndInstantiatePrefilledFormTaskECRequest inValue = new EC_Endpoint_Client.PrefillAgencyEC2.SubmitAndInstantiatePrefilledFormTaskECRequest();
            inValue.Body = new EC_Endpoint_Client.PrefillAgencyEC2.SubmitAndInstantiatePrefilledFormTaskECRequestBody();
            inValue.Body.systemUserName = systemUserName;
            inValue.Body.systemPassword = systemPassword;
            inValue.Body.externalBatchId = externalBatchId;
            inValue.Body.preFillFormTask = preFillFormTask;
            inValue.Body.doSaveFormTask = doSaveFormTask;
            inValue.Body.doinstantiateFormTask = doinstantiateFormTask;
            inValue.Body.caseId = caseId;
            inValue.Body.dueDate = dueDate;
            inValue.Body.instantitedOnBehalfOf = instantitedOnBehalfOf;
            return ((EC_Endpoint_Client.PrefillAgencyEC2.IPreFillAgencyExternalEC2)(this)).SubmitAndInstantiatePrefilledFormTaskECAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EC_Endpoint_Client.PrefillAgencyEC2.SubmitPrefilledFormTasksECResponse EC_Endpoint_Client.PrefillAgencyEC2.IPreFillAgencyExternalEC2.SubmitPrefilledFormTasksEC(EC_Endpoint_Client.PrefillAgencyEC2.SubmitPrefilledFormTasksECRequest request) {
            return base.Channel.SubmitPrefilledFormTasksEC(request);
        }
        
        public EC_Endpoint_Client.PrefillAgencyEC2.ReceiptExternal SubmitPrefilledFormTasksEC(string systemUserName, string systemPassword, string externalBatchId, EC_Endpoint_Client.PrefillAgencyEC2.PrefillFormTaskDetails preFillFormTasksDetails) {
            EC_Endpoint_Client.PrefillAgencyEC2.SubmitPrefilledFormTasksECRequest inValue = new EC_Endpoint_Client.PrefillAgencyEC2.SubmitPrefilledFormTasksECRequest();
            inValue.Body = new EC_Endpoint_Client.PrefillAgencyEC2.SubmitPrefilledFormTasksECRequestBody();
            inValue.Body.systemUserName = systemUserName;
            inValue.Body.systemPassword = systemPassword;
            inValue.Body.externalBatchId = externalBatchId;
            inValue.Body.preFillFormTasksDetails = preFillFormTasksDetails;
            EC_Endpoint_Client.PrefillAgencyEC2.SubmitPrefilledFormTasksECResponse retVal = ((EC_Endpoint_Client.PrefillAgencyEC2.IPreFillAgencyExternalEC2)(this)).SubmitPrefilledFormTasksEC(inValue);
            return retVal.Body.SubmitPrefilledFormTasksECResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EC_Endpoint_Client.PrefillAgencyEC2.SubmitPrefilledFormTasksECResponse> EC_Endpoint_Client.PrefillAgencyEC2.IPreFillAgencyExternalEC2.SubmitPrefilledFormTasksECAsync(EC_Endpoint_Client.PrefillAgencyEC2.SubmitPrefilledFormTasksECRequest request) {
            return base.Channel.SubmitPrefilledFormTasksECAsync(request);
        }
        
        public System.Threading.Tasks.Task<EC_Endpoint_Client.PrefillAgencyEC2.SubmitPrefilledFormTasksECResponse> SubmitPrefilledFormTasksECAsync(string systemUserName, string systemPassword, string externalBatchId, EC_Endpoint_Client.PrefillAgencyEC2.PrefillFormTaskDetails preFillFormTasksDetails) {
            EC_Endpoint_Client.PrefillAgencyEC2.SubmitPrefilledFormTasksECRequest inValue = new EC_Endpoint_Client.PrefillAgencyEC2.SubmitPrefilledFormTasksECRequest();
            inValue.Body = new EC_Endpoint_Client.PrefillAgencyEC2.SubmitPrefilledFormTasksECRequestBody();
            inValue.Body.systemUserName = systemUserName;
            inValue.Body.systemPassword = systemPassword;
            inValue.Body.externalBatchId = externalBatchId;
            inValue.Body.preFillFormTasksDetails = preFillFormTasksDetails;
            return ((EC_Endpoint_Client.PrefillAgencyEC2.IPreFillAgencyExternalEC2)(this)).SubmitPrefilledFormTasksECAsync(inValue);
        }
    }
}
