//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC_Endpoint_Client.IntermediaryInboundStreamed {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AltinnFault", Namespace="http://www.altinn.no/services/common/fault/2009/10")]
    [System.SerializableAttribute()]
    public partial class AltinnFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AltinnErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AltinnExtendedErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AltinnLocalizedErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AltinnErrorMessage {
            get {
                return this.AltinnErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.AltinnErrorMessageField, value) != true)) {
                    this.AltinnErrorMessageField = value;
                    this.RaisePropertyChanged("AltinnErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AltinnExtendedErrorMessage {
            get {
                return this.AltinnExtendedErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.AltinnExtendedErrorMessageField, value) != true)) {
                    this.AltinnExtendedErrorMessageField = value;
                    this.RaisePropertyChanged("AltinnExtendedErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AltinnLocalizedErrorMessage {
            get {
                return this.AltinnLocalizedErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.AltinnLocalizedErrorMessageField, value) != true)) {
                    this.AltinnLocalizedErrorMessageField = value;
                    this.RaisePropertyChanged("AltinnLocalizedErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorGuid {
            get {
                return this.ErrorGuidField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorGuidField, value) != true)) {
                    this.ErrorGuidField = value;
                    this.RaisePropertyChanged("ErrorGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorID {
            get {
                return this.ErrorIDField;
            }
            set {
                if ((this.ErrorIDField.Equals(value) != true)) {
                    this.ErrorIDField = value;
                    this.RaisePropertyChanged("ErrorID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserGuid {
            get {
                return this.UserGuidField;
            }
            set {
                if ((object.ReferenceEquals(this.UserGuidField, value) != true)) {
                    this.UserGuidField = value;
                    this.RaisePropertyChanged("UserGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIdField, value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2013/06", ConfigurationName="IntermediaryInboundStreamed.IIntermediaryInboundExternalECStreamed")]
    public interface IIntermediaryInboundExternalECStreamed {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://www.altinn.no/services/2009/10) of message TestRequest does not match the default value (http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2013/06)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/2009/10/IAltinnContractBase/Test", ReplyAction="http://www.altinn.no/services/2009/10/IAltinnContractBase/TestResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EC_Endpoint_Client.IntermediaryInboundStreamed.AltinnFault), Action="http://www.altinn.no/services/2009/10/IAltinnContractBase/TestAltinnFaultFault", Name="AltinnFault", Namespace="http://www.altinn.no/services/common/fault/2009/10")]
        EC_Endpoint_Client.IntermediaryInboundStreamed.TestResponse Test(EC_Endpoint_Client.IntermediaryInboundStreamed.TestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/2009/10/IAltinnContractBase/Test", ReplyAction="http://www.altinn.no/services/2009/10/IAltinnContractBase/TestResponse")]
        System.Threading.Tasks.Task<EC_Endpoint_Client.IntermediaryInboundStreamed.TestResponse> TestAsync(EC_Endpoint_Client.IntermediaryInboundStreamed.TestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2013/06/I" +
            "IntermediaryInboundExternalECStreamed/SubmitAttachmentStreamedEC", ReplyAction="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2013/06/I" +
            "IntermediaryInboundExternalECStreamed/SubmitAttachmentStreamedECResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EC_Endpoint_Client.IntermediaryInboundStreamed.AltinnFault), Action="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2013/06/I" +
            "IntermediaryInboundExternalECStreamed/SubmitAttachmentStreamedECAltinnFaultFault" +
            "", Name="AltinnFault", Namespace="http://www.altinn.no/services/common/fault/2009/10")]
        EC_Endpoint_Client.IntermediaryInboundStreamed.ReceiptExternalStreamedBE SubmitAttachmentStreamedEC(EC_Endpoint_Client.IntermediaryInboundStreamed.StreamedAttachmentECBE request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2013/06/I" +
            "IntermediaryInboundExternalECStreamed/SubmitAttachmentStreamedEC", ReplyAction="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2013/06/I" +
            "IntermediaryInboundExternalECStreamed/SubmitAttachmentStreamedECResponse")]
        System.Threading.Tasks.Task<EC_Endpoint_Client.IntermediaryInboundStreamed.ReceiptExternalStreamedBE> SubmitAttachmentStreamedECAsync(EC_Endpoint_Client.IntermediaryInboundStreamed.StreamedAttachmentECBE request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Test", WrapperNamespace="http://www.altinn.no/services/2009/10", IsWrapped=true)]
    public partial class TestRequest {
        
        public TestRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TestResponse", WrapperNamespace="http://www.altinn.no/services/2009/10", IsWrapped=true)]
    public partial class TestResponse {
        
        public TestResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StreamedAttachmentECBE", WrapperNamespace="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2013/06", IsWrapped=true)]
    public partial class StreamedAttachmentECBE {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2013/06")]
        public string AttachmentTypeName;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2013/06")]
        public string CheckSum;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2013/06")]
        public string EndUserSystemreference;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2013/06")]
        public string FileName;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2013/06")]
        public string Name;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2013/06")]
        public int ReporteeElementId;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2013/06")]
        public string password;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2013/06")]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2013/06", Order=0)]
        public System.IO.Stream dataStream;
        
        public StreamedAttachmentECBE() {
        }
        
        public StreamedAttachmentECBE(string AttachmentTypeName, string CheckSum, string EndUserSystemreference, string FileName, string Name, int ReporteeElementId, string password, string userName, System.IO.Stream dataStream) {
            this.AttachmentTypeName = AttachmentTypeName;
            this.CheckSum = CheckSum;
            this.EndUserSystemreference = EndUserSystemreference;
            this.FileName = FileName;
            this.Name = Name;
            this.ReporteeElementId = ReporteeElementId;
            this.password = password;
            this.userName = userName;
            this.dataStream = dataStream;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReceiptExternalStreamedBE", WrapperNamespace="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2013/06", IsWrapped=true)]
    public partial class ReceiptExternalStreamedBE {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2013/06", Order=0)]
        public string LastChanged;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2013/06", Order=1)]
        public int ParentReceiptId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2013/06", Order=2)]
        public string ReceiptHistory;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2013/06", Order=3)]
        public int ReceiptId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2013/06", Order=4)]
        public string ReceiptStatusCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2013/06", Order=5)]
        public string ReceiptText;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.altinn.no/services/Intermediary/Shipment/IntermediaryInbound/2013/06", Order=6)]
        public string ReceiptTypeName;
        
        public ReceiptExternalStreamedBE() {
        }
        
        public ReceiptExternalStreamedBE(string LastChanged, int ParentReceiptId, string ReceiptHistory, int ReceiptId, string ReceiptStatusCode, string ReceiptText, string ReceiptTypeName) {
            this.LastChanged = LastChanged;
            this.ParentReceiptId = ParentReceiptId;
            this.ReceiptHistory = ReceiptHistory;
            this.ReceiptId = ReceiptId;
            this.ReceiptStatusCode = ReceiptStatusCode;
            this.ReceiptText = ReceiptText;
            this.ReceiptTypeName = ReceiptTypeName;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IIntermediaryInboundExternalECStreamedChannel : EC_Endpoint_Client.IntermediaryInboundStreamed.IIntermediaryInboundExternalECStreamed, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IntermediaryInboundExternalECStreamedClient : System.ServiceModel.ClientBase<EC_Endpoint_Client.IntermediaryInboundStreamed.IIntermediaryInboundExternalECStreamed>, EC_Endpoint_Client.IntermediaryInboundStreamed.IIntermediaryInboundExternalECStreamed {
        
        public IntermediaryInboundExternalECStreamedClient() {
        }
        
        public IntermediaryInboundExternalECStreamedClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IntermediaryInboundExternalECStreamedClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IntermediaryInboundExternalECStreamedClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IntermediaryInboundExternalECStreamedClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EC_Endpoint_Client.IntermediaryInboundStreamed.TestResponse EC_Endpoint_Client.IntermediaryInboundStreamed.IIntermediaryInboundExternalECStreamed.Test(EC_Endpoint_Client.IntermediaryInboundStreamed.TestRequest request) {
            return base.Channel.Test(request);
        }
        
        public void Test() {
            EC_Endpoint_Client.IntermediaryInboundStreamed.TestRequest inValue = new EC_Endpoint_Client.IntermediaryInboundStreamed.TestRequest();
            EC_Endpoint_Client.IntermediaryInboundStreamed.TestResponse retVal = ((EC_Endpoint_Client.IntermediaryInboundStreamed.IIntermediaryInboundExternalECStreamed)(this)).Test(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EC_Endpoint_Client.IntermediaryInboundStreamed.TestResponse> EC_Endpoint_Client.IntermediaryInboundStreamed.IIntermediaryInboundExternalECStreamed.TestAsync(EC_Endpoint_Client.IntermediaryInboundStreamed.TestRequest request) {
            return base.Channel.TestAsync(request);
        }
        
        public System.Threading.Tasks.Task<EC_Endpoint_Client.IntermediaryInboundStreamed.TestResponse> TestAsync() {
            EC_Endpoint_Client.IntermediaryInboundStreamed.TestRequest inValue = new EC_Endpoint_Client.IntermediaryInboundStreamed.TestRequest();
            return ((EC_Endpoint_Client.IntermediaryInboundStreamed.IIntermediaryInboundExternalECStreamed)(this)).TestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EC_Endpoint_Client.IntermediaryInboundStreamed.ReceiptExternalStreamedBE EC_Endpoint_Client.IntermediaryInboundStreamed.IIntermediaryInboundExternalECStreamed.SubmitAttachmentStreamedEC(EC_Endpoint_Client.IntermediaryInboundStreamed.StreamedAttachmentECBE request) {
            return base.Channel.SubmitAttachmentStreamedEC(request);
        }
        
        public string SubmitAttachmentStreamedEC(string AttachmentTypeName, string CheckSum, string EndUserSystemreference, string FileName, string Name, int ReporteeElementId, string password, string userName, System.IO.Stream dataStream, out int ParentReceiptId, out string ReceiptHistory, out int ReceiptId, out string ReceiptStatusCode, out string ReceiptText, out string ReceiptTypeName) {
            EC_Endpoint_Client.IntermediaryInboundStreamed.StreamedAttachmentECBE inValue = new EC_Endpoint_Client.IntermediaryInboundStreamed.StreamedAttachmentECBE();
            inValue.AttachmentTypeName = AttachmentTypeName;
            inValue.CheckSum = CheckSum;
            inValue.EndUserSystemreference = EndUserSystemreference;
            inValue.FileName = FileName;
            inValue.Name = Name;
            inValue.ReporteeElementId = ReporteeElementId;
            inValue.password = password;
            inValue.userName = userName;
            inValue.dataStream = dataStream;
            EC_Endpoint_Client.IntermediaryInboundStreamed.ReceiptExternalStreamedBE retVal = ((EC_Endpoint_Client.IntermediaryInboundStreamed.IIntermediaryInboundExternalECStreamed)(this)).SubmitAttachmentStreamedEC(inValue);
            ParentReceiptId = retVal.ParentReceiptId;
            ReceiptHistory = retVal.ReceiptHistory;
            ReceiptId = retVal.ReceiptId;
            ReceiptStatusCode = retVal.ReceiptStatusCode;
            ReceiptText = retVal.ReceiptText;
            ReceiptTypeName = retVal.ReceiptTypeName;
            return retVal.LastChanged;
        }
        
        public System.Threading.Tasks.Task<EC_Endpoint_Client.IntermediaryInboundStreamed.ReceiptExternalStreamedBE> SubmitAttachmentStreamedECAsync(EC_Endpoint_Client.IntermediaryInboundStreamed.StreamedAttachmentECBE request) {
            return base.Channel.SubmitAttachmentStreamedECAsync(request);
        }
    }
}
